x/name/keeper/keeper.go
x/name/keeper/keeper_test.go

Change check to only enforce size constraint if it isn't a valid UUID.

Add support for uuid names

---

cmd/provenanced/cmd/testnet.go

This adds the provenance specific denomination metadata to the genesis file for the testnet.

Add provenance denom metadata to testnet

---

CHANGELOG.md
app/app.go

This PR adds no-op upgrade handlers for a range of testnet release versions to make cosmovisor happy.
This addresses only one of a set of changes required for #30 
---

Use no-op upgrade handlers for testnet releases

---

app/app.go

This PR updates an off-by-one bug that prevented zero-value patch releases (e.g. v0.2.0) from getting default upgrade handlers set.
closes: #73

Fix upgrade handler bug

---

CHANGELOG.md
app/app.go

This PR:
* Removes the automatic setting of upgrade handlers.
* Adds an explicit upgrade handler for the upcoming `v0.1.5` release.
closes: #116

Bugfix: Remove auto no-op handlers

---

x/marker/keeper/marker.go
x/marker/keeper/querier.go

Removes todo comments for this feature and closes #45.  This feature can not be implemented in the metadata module without adding a dependency on the metadata module (not a great idea).  The ValueOwner query support is implemented in metadata already (https://github.com/provenance-io/provenance/blob/82469ece04db9c03f84266c7bd023c3d4fddd82a/x/metadata/keeper/query_server.go#L169)
The Delete method of the Marker only assigns the Destroyed status to a marker (it does not fully remove it) so references can be maintained to existing scopes via value-ownership.
closes: #45 
---

remove todo comments for marker value owner

---

cmd/provenanced/cmd/root.go

Currently the `keys` sub command of `provenance` uses the default flag value of 118 which matches cosmos.  Due to the way this default is setup it is not overridden properly with the `-t` flag that switches to testnet/mainnet.  Because of this the default value should at least always match a Provenance network
closes: #XXXX
---

update for provenance key command using wrong default coin type

---

app/upgrades.go

0.2.1 upgrade handler pulled existing parameters for marker module which fails due to new parameter that is missing.  This update changes behavior such that params are set directly to the defaults to avoid this read error.
closes: #155 
---

Update upgrade handler to avoid unset param

---

app/app.go
app/upgrades.go

Currently, the store loader will load every run. This PR assures that the customStoreLoader only runs during upgrades detected and driven by the 'upgrade-info.json' file.
IMPACT: Since no upgrade handler defined any store upgrades, there is no negative impact as long as this is fixed before an upgrade is added that mutates the kvstore list.
---

Stop custom store loader from loading everytime

---

Makefile
buf.yaml

Remove `version: v1beta1` from `buf.yaml` and add `check` back into the `make proto-lint` command.
Both of those changes were due to warnings I was getting when using buf version `0.37.0` instead of `0.11.0`.
---

Undo recent make proto-lint changes

---

CHANGELOG.md
x/attribute/client/cli/cli_test.go
x/attribute/keeper/genesis.go
x/attribute/keeper/keeper.go
x/attribute/keeper/keeper_test.go
x/attribute/module.go
x/attribute/types/attribute.go
x/attribute/types/attribute_test.go
x/attribute/types/genesis.go
x/attribute/types/msgs.go

Refactor existing Validate method in x/attribute/types/attribute.go to be ValidateBasic to follow sdk standard. 
closes: #44 
---

Refactor attribute validation

---

CHANGELOG.md
x/marker/wasm/encode.go

This PR allows smart contracts to withdraw any fund from a marker account (not just the marker coin). In addition, denoms are now validated with the cosmos sdk, instead of just empty string checks.
closes: #151

Support wasm marker withrawals for any denom/amount

---

CHANGELOG.md
internal/legacy/v040/migrate.go

Assigns migration genesis parameters for IBC modules during migrate process from v039 to v040 chains.  Values are based off of an enabled IBC that supports connections to solo-machine and tendermint consensus.  It is probable that only tendermint consensus based chains will be allowed in the final mainnet configuration.
closes: #102
---

set ibc params in migration script for v039 chains

---

CHANGELOG.md
x/metadata/client/cli/query.go

* Adds pagination flags to the CLI Metadata query commands. The flags were being looked for already, but just weren't added to the commands and so couldn't be used.
* Add some aliases for various query commands.
List of metadata query commands and their aliases:
```
metadata       md
params         p
get            g
all            a
scope          sc, scopes
session        se, sessions
record         r, records
scopespec      ss, scopespecification, scopespecs, scopespecifications
contractspec   cs, contractspecification, contractspecs, contractspecifications
recordspec     rs, recordspecs, recspec, recspecs, recordspecification, recordspecifications
owner          o, ownership
valueowner     vo, valueownership
locator        l, locators
```
---
Before we can merge this PR, please make …

Add Pagination flags to CLI Metadata query commands.

---

CHANGELOG.md
x/metadata/legacy/v039/crypto.go
x/metadata/legacy/v040/migrate_test.go
x/metadata/types/p8e.go
x/metadata/types/p8e_test.go

Metadata module parsePublicKey was not correctly initializing the PubKey type causing a panic when converting base64 key to pubkey and address.
closes: #225 
---

Parse public key PubKey type incorrectly initialized 

---

CHANGELOG.md
x/metadata/types/p8e.go
x/metadata/types/p8e_test.go

* Rename `getSessionSpecID` to `getContractSpecID` because there's no such thing as a session spec.
* Fix `getContractSpecID` to use the correct type prefix.
* Correctly set the `SessionId` instead of setting the wrong field.
---

Fix incorrect conversion pieces in P8EMemorializeContract

---

CHANGELOG.md
x/metadata/types/p8e.go

* Allow the contract spec id to be communicated through either the `contract.Spec.DataLocation.Ref.Hash` or `contract.Definition.ResourceLocation.Ref.Hash` fields.
* Allow the value of those fields to be either a hash or the bech32 contract spec id string.
---

Loosen Contract Spec ID p8e Conversion

---

go.mod
go.sum

Updates cosmos sdk to 0.42.4 as a non-breaking change to the v1.0.x release.
closes: #235 
---

update cosmos sdk to 0.42.4

---

CHANGELOG.md
x/marker/handler.go

The marker handler was missing a case for `MsgSetDenomMetadataRequest`. This PR fixes that.
---

Add MsgSetDenomMetadataRequest to the marker handler

---

CHANGELOG.md
cmd/provenanced/cmd/init.go

The recover flag was not wired into the init command to recover a key from mnemonic.
closes: #254 
---

Add recovery to init

---

CHANGELOG.md
x/marker/types/msg.go

Relaxes signing constraint on transfer operations for markers.  Request must be signed by an administrator that possess transfer authority on the marker but the from account signature is no longer required.  See #246 for discussion.
closes: #246 
---

relax signing constraint on marker transfer

---

CHANGELOG.md
x/marker/keeper/denom.go
x/marker/keeper/denom_test.go
x/marker/keeper/keeper_test.go
x/marker/keeper/marker.go
x/marker/keeper/msg_server.go
x/marker/keeper/params.go
x/marker/types/denom.go
x/marker/types/denom_test.go
x/marker/types/params.go
x/marker/types/params_test.go

Standardize on always using the anchored regex for denom evaluation in markers similar to the upstream SDK approach
https://github.com/iramiller/cosmos-sdk/blob/512b533242d34926972a8fc2f5639e8cf182f5bd/types/coin.go#L625
closes: #258
---

always anchor unresticted denom expressions

---

CHANGELOG.md
x/metadata/keeper/record.go
x/metadata/legacy/v040/migrate.go
x/metadata/legacy/v040/migrate_test.go
x/metadata/types/p8e.go
x/metadata/types/p8e_test.go

For `WriteP8EContractSpec`, use a hash of the proto as the source hash. Also use the first 16 bytes of that hash as the uuid. This more closely reflects what was previously done.
For `P8EMemorializeContract` get the contract spec uuid from the `contract.Spec` area. Also use the `contract.Definition` for the session name (instead of using the `.Spec`).
Fix the `SetRecord` event key (was `scope_id` but should be `record_id`).
closes: #275
---

Fix p8e contract specification uuid.

---

CHANGELOG.md
Makefile
proto/provenance/attribute/v1/attribute.proto
x/attribute/handler_test.go
x/attribute/keeper/keeper.go
x/attribute/keeper/msg_server.go
x/attribute/types/attribute.pb.go
x/attribute/types/events.go
x/metadata/types/tx.pb.go

Implementation of typed events and metrics for the attribute module.
closes: #86 
---

 Add typed events and metrics to the Attribute module

---

CHANGELOG.md
cmd/provenanced/cmd/addresses.go
cmd/provenanced/cmd/addresses_test.go
x/metadata/types/address.go

Fix the CLI metaaddress encode and decode commands.
1.  Fix expected number of arguments issue.
2.  Enable support for record specs.
closes: #321
---

Fix CLI metaaddress encode and decode

---

CHANGELOG.md
x/metadata/keeper/keeper.go
x/metadata/keeper/keeper_test.go
x/metadata/keeper/msg_server.go

…preserve its owners and value owners. Also only add to the data access list (instead of fully overwritting it).
This PR makes the following changes to the processing done during P8EMemorializeContract:
1.  If there's already a Scope with the given scope id, don't update the `Owners` or `ValueOwnerAddress` fields.
2. If there's already a scope with the given scope id, copy it's existing `DataAccess` values and add any new ones that might be missing (but don't remove any existing values).
Currently, during a P8EMemorializeContract call, the `Scope.Owners`, `Scope.ValueOwnerAddress`, and `Scope.DataAccess` values are populated using only info in the `MsgP8EMemorializeContractRequest`.
This has caused a problem in the following scenario:
1) `MsgP8EMemorializeContractRequest` is called with a …

P8EMemorializeContract: Limit scope field changes.

---

CHANGELOG.md
app/app.go
app/params/weights.go
internal/antewrapper/tracing_meter.go
x/attribute/keeper/keeper.go
x/attribute/keeper/keeper_legacy_test.go
x/attribute/keeper/keeper_test.go
x/attribute/keeper/msg_server.go
x/attribute/module.go
x/attribute/simulation/decoder.go
x/attribute/simulation/decoder_test.go
x/attribute/simulation/operations.go
x/attribute/simulation/operations_test.go
x/attribute/types/expected_keepers.go
x/attribute/types/keys.go
x/attribute/types/keys_test.go

Adds simulation support to the attribute module
closes: #25 
---

Attribute module simulation support

---

CHANGELOG.md
x/metadata/handler_test.go
x/metadata/keeper/msg_server.go

The `DeleteScopeOwner` endpoint was saving the existing scope instead of the updated one. This fixes that.
---

Fix DeleteScopeOwner not working

---

x/metadata/spec/02_state.md

The metadata module spec state documentation incorrectly had the scope specification type byte as `0x03` and the contract specification type byte as `0x04`.
The correct values are:
- Scope specification: `0x04`
- Contract Specification: `0x03`
See: https://github.com/provenance-io/provenance/blob/main/x/metadata/types/keys.go#L68-L71
---

Fix the documented type bytes for scope specifications and contract specifications

---

.github/workflows/sims.yml

Fixes a warning in both the `test-sim-import-export` and `test-sim-multi-seed-short` Github actions.
> Unexpected input(s) 'SUFFIX_FILTER', valid inputs are ['GITHUB_TOKEN', 'DOT', 'BASE', 'RELATIVE', 'DIFF_FILTER', 'FORMAT', 'ESCAPE_JSON', 'SEPARATOR', 'PATTERNS', 'MINIMATCH_OPTION_NOBRACE', 'MINIMATCH_OPTION_NOGLOBSTAR', 'MINIMATCH_OPTION_DOT', 'MINIMATCH_OPTION_NOEXT', 'MINIMATCH_OPTION_NOCASE', 'MINIMATCH_OPTION_MATCH_BASE', 'MINIMATCH_OPTION_NONEGATE', 'FILES', 'SUMMARY_INCLUDE_FILES', 'ABSOLUTE', 'SET_ENV_NAME', 'SET_ENV_NAME_FILTERED_DIFF', 'SET_ENV_NAME_MATCHED_FILES', 'SET_ENV_NAME_COUNT', 'SET_ENV_NAME_INSERTIONS', 'SET_ENV_NAME_DELETIONS', 'SET_ENV_NAME_LINES', 'DIFF_DEFAULT', 'FILTERED_DIFF_DEFAULT', 'MATCHED_FILES_DEFAULT', 'COUNT_DEFAULT', 'INSERTIONS_DEFAULT', …

Fix warning on a couple sims actions.

---

CHANGELOG.md
x/marker/keeper/proposal_handler.go
x/marker/keeper/proposal_handler_test.go

This PR addresses the issue creating non-coin type markers through governance addmarker proposals.
closes: #431 
---

Fix add marker governance proposal non-coin type marker creation

---

CHANGELOG.md
cmd/provenanced/cmd/root.go

Add home directory to for createAppAndExport to use.  It was using a hard coded `""`, but now will check to see if home path was set from cli.
closes: #457 
---

Add setting of home path to createAppAndExport app setup

---

CHANGELOG.md
x/metadata/keeper/record.go

Remove some code from the record keeper persistent validation that was creating a slice and map that wasn't being used for anything. I'm pretty sure, at one point, it was part of a uniqueness restriction that wasn't actually wanted, but didn't get fully removed.
closes: #471
---

Remove some unneeded code from record keeper.

---

CHANGELOG.md
app/params/amino.go
app/params/proto.go
internal/tools/tools.go
x/metadata/client/cli/cli_page_test.go
x/metadata/keeper/query_server.go

Refactor the metadata module's `OSAllLocators` and `OSLocatorsByURIRequest` queries to fully support the pagination features.
closes: #401
closes: #402 
---

Enable full pagination support for the metadata OS Locator queries

---

CHANGELOG.md
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go

When using a packed config, provide the global-labels to viper in the same way they're expected in the cosmos `GetConfig` function.
closes: #487
---

Fix panic when using packed config

---

CHANGELOG.md
x/marker/keeper/marker.go

- Changed to compare on `coin.Amount` as `sdk.Int` type vs `coin.Amount.Uint64()`.
closes: #489
---

489 marker supply gt uint64 causes panic

---

CHANGELOG.md
x/marker/keeper/marker.go

Cherry pick issue 489 `Adding a marker with more than 2^64 coins and minting more panics` from main to v1.7.x
closes: #XXXX
---

Cherry pick 489 Adding a marker with more than 2^64 coins and minting more panics

---

CHANGELOG.md
cmd/provenanced/config/interceptor.go
cmd/provenanced/config/manager.go

…that the configured values can be used as needed.
The logger was being created before the configuration was being loaded. That made it so that the configured `log_level` and `log_format` were being ignored and only flags and defaults were used for them.
This fix moves the logger creation and setting until later, once the configs have been loaded.
---

Fix logger ignoring configuration

---

cmd/provenanced/cmd/root.go

The Cosmos-SDK is removing the `client.ReadHomeFlag` function. In preparation of that, replace our use of it with the little bit that it does.
Note: I skipped the CHANGELOG entry because there's no functionality change. It's just removing a function call and replacing it with what the lines of the function (and changing a variable name). I'll add one if requested, though.
---

Replace call to client.ReadHomeFlag

---

CHANGELOG.md
app/upgrades.go

Re-opened issue to add upgrade change to attribute's max value length and add changelog entries.
closes: #616
---

616 add attribute max length change

---

.github/workflows/build-and-publish-proto-bindings.yml
CHANGELOG.md
cmd/provenanced/cmd/root_test.go
internal/antewrapper/msg_fees_decorator_test.go
internal/antewrapper/testutil_test.go
x/attribute/client/cli/cli_test.go
x/attribute/client/cli/tx.go
x/attribute/client/rest/grpc_query_test.go
x/attribute/client/rest/tx.go
x/attribute/handler_test.go
x/attribute/keeper/keeper.go
x/attribute/keeper/keeper_test.go
x/attribute/keeper/msg_server.go
x/attribute/keeper/querier.go
x/attribute/keeper/query_server.go
x/attribute/legacy/v042/store.go
x/attribute/legacy/v042/store_test.go
x/attribute/simulation/decoder_test.go
x/attribute/simulation/operations.go
x/attribute/simulation/operations_test.go
x/attribute/types/attribute.go
x/attribute/types/keys.go
x/attribute/types/msgs.go
x/attribute/types/msgs_test.go
x/attribute/wasm/encode.go
x/attribute/wasm/query.go

Updates validation and handling of the `Attribute.Address` field to allow it to be a scope metadata address.
closes: #631 
---

Allow attributes to be associated with scopes.

---

.github/workflows/build-and-publish-proto-bindings.yml
CHANGELOG.md
app/upgrades.go
cmd/provenanced/cmd/root_test.go
internal/antewrapper/msg_fees_decorator_test.go
internal/antewrapper/testutil_test.go
x/attribute/client/cli/cli_test.go
x/attribute/client/cli/tx.go
x/attribute/client/rest/grpc_query_test.go
x/attribute/client/rest/tx.go
x/attribute/handler_test.go
x/attribute/keeper/keeper.go
x/attribute/keeper/keeper_test.go
x/attribute/keeper/msg_server.go
x/attribute/keeper/querier.go
x/attribute/keeper/query_server.go
x/attribute/legacy/v042/store.go
x/attribute/legacy/v042/store_test.go
x/attribute/simulation/decoder_test.go
x/attribute/simulation/operations.go
x/attribute/simulation/operations_test.go
x/attribute/types/attribute.go
x/attribute/types/attribute_test.go
x/attribute/types/keys.go
x/attribute/types/msgs.go
x/attribute/types/msgs_test.go
x/attribute/wasm/encode.go
x/attribute/wasm/query.go

Backports #625  #633 and #632 into 1.8.x
closes: #XXXX
---

Backport scope/attributes, gov deposit, and java distribution changes

---

CHANGELOG.md
go.mod
go.sum

This PR pulls in the provenance fork of wasmd.  This will ensure that old contract addresses of length 20 (< v1.8.0) are still supported.  
Changes on wasmd fork: https://github.com/CosmWasm/wasmd/compare/v0.22.0...provenance-io:v0.22.0-pio-address-fix?expand=1
closes: #662 
---

Fix contract address length support

---

CHANGELOG.md
app/app.go
cmd/provenanced/cmd/root.go

closes: #670
When an error is encountered during `provenanced start`:
* Before this change: the error is printed, then usage is printed, then the program exits.
* After this change: the error is printed, then the program exits.
You can still get usage info for the command using either `provenanced help start` or `provenanced start --help`.
---

Prevent usage from being printed when the start command encounters an error

---

x/metadata/wasm/types.go

This PR fixes the scope owners modification from wasm contracts issue that causes an array index bounds error.
closes: #675 
---

Fix array bounds issue with wasm scope owners modification

---

.github/workflows/lint.yml

Use go version 1.17 for the lint action in 1.8.x
---

Use go version 1.17 for the lint action in 1.8.x.

---

CHANGELOG.md
cmd/provenanced/cmd/init.go
x/marker/spec/09_params.md
x/marker/types/params.go
x/marker/types/params_test.go

Changes the default unrestricted denom size from 64 to 83.  This add the new size to the generated genesis file.
closes: #719 
---

Update marker denom regex to size 83

---

.github/workflows/release.yml

Workaround for issue with GitHub actions. Force downgrade of OSX Homebrew.
---

Workaround for GitHub Actions issue

---

CHANGELOG.md
x/metadata/keeper/scope.go
x/metadata/keeper/scope_test.go

Allow authz grants to work for non-marker scope value owners.
closes: #755
---

Allow authz grants to work for scope value owners.

---

scripts/proto-update-deps.sh

Conf.io changed their release naming for the ics123 library which `proofs.proto` comes from [as seen here](https://github.com/confio/ics23/releases). This change breaks the `proto-update-deps` script in the `scripts/` directory.  I have updated the path in the script. 
Also, the bash script was not exiting correctly on error which was resulting in the `proofs.proto` file to be overwritten with `404: File Not Found`. The curl commands were updated to use the `-f` flag and also removed the `|| exit` conditions since the bash script is already setup with `set -e` which will fail on any non 0 exits. 
This is a duplicate of https://github.com/provenance-io/provenance/pull/762 except with signed commits as required for merging.
---
Before we can merge this PR, please make sure that all the …

Fix the proto-update-deps script.

---

app/upgrades.go
go.mod
go.sum

Update Cosmos SDK (0.45.3-pio-2) to fix bug with detecting last upgrade. Also removed unused upgrade handler originally added to bypass panic caused by bug.
Addresses [#11707](https://github.com/cosmos/cosmos-sdk/issues/11707)
---

Update Cosmos SDK to v0.45.3-pio-2 for 11707 bugfix

---

Makefile
docs/Building.md
scripts/m1_librdkafka_install.sh

The m1 kafka dependencies aren't included by go-kafka. This requires the user to manually install them and setup their machine in order to build and run provenance. The m1_librdkafka_install.sh script has been added to install all the needed dependencies, and it will also notify the user if they need to update PKG_CONFIG_PATH. The makefile has been updated to include `make librdkafka` and it will only call this script on M1s.
Documentation has been updated to include the new make command and setting the PKG_CONFIG_PATH variable.
closes: #812 
---

librdkafka m1 dependencies

---

CHANGELOG.md
app/upgrades.go

Create a `mango-rc2` upgrade handler and make create an empty `mango` upgrade.
Version 1.11.1-rc1 shipped with an empty `mango` upgrade, but there's a migration in the bank module that's needed as well as setting the default conversion rate. So we need a `mango-rc2` to do that so that it can be applied just to testnet. But the mainnet upgrade can still be just `mango` because it's got the code too.
This isn't needed in the `main` branch because the `mango` handler there is sufficient. We only need this `mango-rc2` one here because `mango` shipped to testnet with `v1.11.1-rc1` but it was empty.
---

Create Mango rc2 handler.

---

.github/workflows/codeql-analysis.yml

This updates the CodeQL workflow to run on release branches. It also stops it from doing javascript code analysis.
---

Update CodeQL workflow to run on release branches and only do golang.

---

.github/workflows/rosetta.yml

The Rosetta workflow is required to pass before a PR can be merged. But in some cases, there's nothing changing that might alter the outcome. So, similar to when we skip the unit tests, also skip the rosetta test.
Since it's a required step, the workflow can't be skipped completely; we still need a success from it. But if there aren't any code changes, skip the actual test part.
---

Limit the running of the rosetta github workflow test

---

.github/workflows/release.yml

Sometime between Thursday June 23 and This morning (Monday June 27), the mac notarization step stopped working. This PR disables that step so we can get this RC out and tested.
This is one of the very rare cases where merging into the release branch is appropriate. We hope to have the root cause of the failure ironed out by the time the actual release happens. By merging it into this the `release/v1.11.1-rc4` branch, we don't have to worry about undoing it in the `.x` branch before release. However, it's a change that might need to be applied to any other RC branches, but I'm hopeful this will be our last RC for this branch.
---
checked off. If any of the checklist items are not applicable, please leave …

Disable mac binary notarization.

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos-SDK to v0.45.4-pio-2 (from v0.45.4-pio-1) to fix a non-deterministic map iteration.
---

Update Cosmos-SDK version to v0.45.4-pio-2 (from v0.45.4-pio-1) (main).

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos-SDK to v0.45.4-pio-2 (from v0.45.4-pio-1) to fix a non-deterministic map iteration.
---

Bump Cosmos-SDK to v0.45.4-pio-2 (from v0.45.4-pio-1) (release/v1.11.x)

---

CHANGELOG.md

Pull in all changes in the `release/v1.11.x` branch (just after creating release `v1.11.1`) back into `main`.
The only thing there is the changelog!
---

Merge release/v1.11.x back into main

---

CHANGELOG.md
x/msgfees/client/cli/query.go

Simple fix to allow standard flags to be used with the msg fees cli params command.
closes: #936 
---

Support standard flags on msgfees cli params query

---

.github/CODEOWNERS

Update the codeowners file to use the `@provenance-io/blockchain-core` group. The `@egaxhaj-figure` entry is not part of the group, and is being removed because it's no longer needed. The `@channa-figure` entry is not yet part of the group, but will be added to the group.
This will add the following users as codeowners: `@SpicyLemon` (me), `@jazzy-figure`, `@ktally-figure`.
It also removes the "secondary" entry containing `@mtps`, and `@jdfigure`. The `*` at the start of those lines is a glob for file matching. The last match is the one that gets used. So that line would only ever get used if the primary entry below it were completely removed.
Here's a link to the group members: https://github.com/orgs/provenance-io/teams/blockchain-core/members
---
Before we can merge this PR, please …

Update codeowners to use the blockchain-core group.

---

CHANGELOG.md
client/rosetta/rosetta-ci/Dockerfile
docker/blockchain/Dockerfile
networks/dev/blockchain-dev/Dockerfile
networks/local/blockchain-local/Dockerfile

Currently the "buster" image is in use in many docker files, this needs to be replaced with "bullseye" as the current security updates for "buster" end July 2022.
closes: #963 
---

update docker images from buster to bullseye

---

CHANGELOG.md
cmd/provenanced/config/filenames.go
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go

closes: #989 
If the config directory has a `custom.toml` file, also load it with the rest of the config stuff. This file isn't managed by the `provenanced config` command so that it can be used for hidden/optional configuration pieces.
This PR also better wraps the errors returned by the manager (rather than always creating a new generic error).
---

Load custom.toml if it exists.

---

docs/proto-docs.md
proto/provenance/expiration/v1/genesis.proto
proto/provenance/expiration/v1/tx.proto
x/expiration/client/cli/cli_test.go
x/expiration/client/cli/tx.go
x/expiration/keeper/keeper.go
x/expiration/keeper/msg_server.go
x/expiration/types/genesis.pb.go
x/expiration/types/msgs.go
x/expiration/types/tx.pb.go

Adds a transaction that allows a user to execute expiration logic.
closes: #1048
---

Add expiration invocation transaction to existing scaffolding

---

internal/antewrapper/ante.go
internal/handlers/msg_service_router.go

closes: #1099
This fix bypasses the `consumeMsgFees` stuff in the message service router when the gas meter isn't a fee gas meter. Basically, before this PR, an error was returned in that case, which turned into a panic. After this PR, nil is returned in that case (and no attempts are made to consume any message-based fees).
Similar to #1102, no unit test for it, but I tested this in the same way (`make clean build run-config && ./scripts/upgrade-config.sh && make run` then use the script from #1097). Again, it now makes it to the upgrade height and (expectedly) halts for the upgrade.
---

Fix gov proposal end-of-voting-period consensus failure.

---

app/sim_bench_test.go
app/sim_test.go

This PR fixes the sims that broke because IBC assumes a parameter is defined, panicking if not, and it wasn't in some of our sims.
---

Fix the sims that broke because IBC makes some assumptions.

---

CHANGELOG.md
app/app.go
go.mod
go.sum
internal/antewrapper/provenance_fee.go
internal/handlers/aggregate_events.go
internal/handlers/aggregate_events_test.go
internal/handlers/msg_fee_invoker.go
internal/handlers/msg_service_router_test.go
x/msgfees/keeper/keeper.go

Versions <= v1.12 have a fee event that is dispatched at the beginning of the transaction that is unreliable.  This is due to the fact that it is emitting the total amount of fee that is sent with the transaction.  The case where this fails to be accurate is when the transaction fails at the ante handler level.  This is because only gas_wanted * min_gas_cost is charged.
This PR also dispatches the events from the distribution of msg based fees and sweeping of the remained fees.  These where suppressed in versions <= 1.12
closes: #1092
---

Update fee event to contain total charge and emit send coin events

---

internal/antewrapper/msg_fees_decorator.go
internal/antewrapper/provenance_fee.go

closes: #1110
lot's of logs coming from
ctx.Logger().Debug("In ProvenanceDeductFeeDecorator", "GasConsumed", ctx.GasMeter().GasConsumed())
a proper fix would be for the fee gas meter to inherit the log level of the caller but easier fix is just to remove them
Fee gas meter logs every-time it is called
// GasConsumed reports the amount of gas consumed at Log.Info level
func (g *FeeGasMeter) GasConsumed() sdkgas.Gas {
usage := "tracingGasMeter:\n  Purpose"
for i, d := range g.used {
usage = fmt.Sprintf("%s\n   - %s (x%d) = %d", usage, i, g.calls[i], d)
}
usage = fmt.Sprintf("%s\n  Total: %d gas", usage, g.base.GasConsumed())
g.log.Info(usage)
return g.base.GasConsumed()
}
Removing those logs would lead to saner logs
10:14PM INF tracingGasMeter:
Purpose
- ReadFlat (x36) = 36000
- ReadPerByte …

removing debug loggers.

---

CHANGELOG.md
x/name/spec/01_concepts.md

Slightly tweaks the name module's documentation on the restrictions on a name.
closes: #808 
---

Small tweaks to the name restrictions documentation.

---

CHANGELOG.md
RELEASE_CHANGELOG.md

Fixes the date in the 1.13.0-rc2 headers.
I made this change locally and forgot to push it up before merging #1184.
---

Fix the 1.13.0-rc2 date

---

CHANGELOG.md
cmd/provenanced/cmd/root.go

Make it so that the `iavl-disable-fastnode` config field/flag is actually used.
Prior to this, it was just always using the default.
---

Provide the iavl-disable-fastnode app option

---

CHANGELOG.md
go.mod
go.sum

This PR bumps Cosmos-SDK to v0.45.10-pio-3 (from v0.45.10-pio-2).
v0.45.10-pio-2 includes a fix for a bug the multistore that sometimes causes db corruption.
This is only needed in the release/v1.12.x branch in prep for v1.12.2.
---

Bump Cosmos to v0.45.10-pio-3 for 1.12.x

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos-SDK to `v0.46.3-pio-2` (from `v0.46.3-pio-1`).
This brings in a fix for a bug that can occur during the iavl upgrade.
---

Bump Cosmos-SDK to v0.46.3-pio-2 (from v0.46.3-pio-1).

---

CHANGELOG.md
go.mod
go.sum

This bumps Cosmos to v0.45.10-pio-4 (from v0.45.10-pio-3) to get an updated iavl version that fixes a possible source of app hash mismatches using the updated IAVL stores.
---

1.12.x: Bump Cosmos to v0.45.10-pio-4

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos-SDK to v0.46.3-pio-3 (from v0.46.3-pio-2).
All this really does is bump iavl to v0.19.4 (from v0.19.3). v0.19.4 fixes a possible app hash mismatch at some point (probably only during the upgrade).
---

Bump Cosmos-SDK to v0.46.3-pio-3 (from v0.46.3-pio-2).

---

CHANGELOG.md
go.mod
go.sum

This applies the following PRs to release/v1.13.x:
* #1201 
* #1206
---

Backport 1.13: Bump Cosmos-SDK to v0.46.3-pio-2 (from v0.46.3-pio-1)

---

CHANGELOG.md
go.mod
go.sum

Bump cosmos-sdk to `v0.46.3-pio-4` (from `v0.46.3-pio-3`).
---

Bump Cosmos-SDK to v0.46.3-pio-4

---

CHANGELOG.md
app/upgrades.go
x/msgfees/keeper/params.go

The ConversionFeeDenom is missing in the GetParams() method of the msgfees module.
closes: #1214
---

ConversionFeeDenom param missing from GetParams in MsgFees module

---

.github/workflows/codeql-analysis.yml
CHANGELOG.md
RELEASE_CHANGELOG.md
client/docs/swagger-ui/swagger.yaml
client/docs/swagger_third_party.yaml
cmd/provenanced/cmd/root.go
go.mod
go.sum
third_party/proto/cosmos/auth/v1beta1/query.proto

This PR marks `v1.13.0-rc4` in the changelog and release changelog.
This PR also backports the following into `release/v1.13.x`:
* #1229
* #1226 
* #1209
It also brings the `v1.12.2` section (from `main` and `release/v1.12.x`) into the changelog.
---

Mark v1.13.0-rc4 and backport v1.13: sdk to v0.46.4-pio-1, codeQL, and pruning command

---

CHANGELOG.md
app/upgrades.go

Merge v1.13.0-rc5 back to main for the updated changelog and fixed `ochre-rc2` upgrade handler.
---

v1.13.0-rc5 back to main.

---

CHANGELOG.md
RELEASE_CHANGELOG.md

This PR targets `release/v1.13.x` and updates the changelog and release changelog by combining the release candidate entries into a single `v1.13.0 entry. It also adds details about REST endpoints that have been removed.
Here's a couple links to what the two files look like now:
* [CHANGELOG.md](https://github.com/provenance-io/provenance/blob/dwedul/1.13.0-changelog/CHANGELOG.md)
* [RELEASE_CHANGELOG.md](https://github.com/provenance-io/provenance/blob/dwedul/1.13.0-changelog/RELEASE_CHANGELOG.md)
closes: #1213
---

Combine 1.13.0-rc changelog entries into a single v1.13.0 entry.

---

CHANGELOG.md

This PR merges `release/v1.13.x` back into `main`. The only thing to bring back is the updated changelog reflecting the release of `v1.13.0`.
---

Update main to reflect v1.13.0 release

---

.github/workflows/release.yml
CHANGELOG.md
Makefile

closes: #1264 
This updates the "Provenance Build and Release" Github Action to include a job that builds dbmigrate as an artifact and includes it in the release artifiacts. A few `Makefile` targets are added to help facilitate this.
---

Build dbmigrate as an artifact

---

CHANGELOG.md
go.mod
go.sum

Bump cosmos-sdk to v0.46.6-pio-2 (from v0.46.6-pio-1).
---

Bump cosmos-sdk to v0.46.6-pio-2 (from v0.46.6-pio-2).

---

CHANGELOG.md
docs/proto-docs.md
internal/handlers/msg_service_router.go
internal/handlers/msg_service_router_test.go
proto/provenance/msgfees/v1/tx.proto
x/msgfees/keeper/keeper_test.go
x/msgfees/types/fee.go
x/msgfees/types/msgs.go
x/msgfees/types/tx.pb.go
x/msgfees/wasm/encode.go

this PR implements https://github.com/provenance-io/provenance/issues/1263  …per request, still keeping bips as an option but for now it all goes to the recipient, see comment on AssessCustomMsgFeeBips  
```
// AssessCustomMsgFeeBips is the bips the recipient will get
// This should be a message level data (present in TypeAssessCustomMsgFee = assess_custom_msg_fee) i think so that it can be defined by the smart contract writer
// or at the very least it can be a module param.
// for now i am hard coding it to avoid breaking any clients and because of this ticket https://github.com/provenance-io/provenance/issues/1263
AssessCustomMsgFeeBips = 10_000
```
created follow up issue if we want to still have some kind of split in the future https://github.com/provenance-io/provenance/issues/1268 …

Send full custom msg fee to recipient instead of 50/50 split with module.

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos-SDK to v0.46.6-pio-3 (from v0.46.6-pio-2).
This is only needed in `release/v1.13.x`. The `main` branch uses an SDK version that already includes these changes.
---

Bump Cosmos-SDK to v0.46.6-pio-3 (from v0.46.6-pio-2).

---

CHANGELOG.md
networks/ibc/docker-compose.yml

Add a port forward for the ibc1 docker container to allow reaching its grpc port. This is intended to better allow testing for apps that need to talk to both a private and public zone directly.
---

Assign port 9091 for ibcnet ibc1 to allow reaching grpc

---

app/upgrades.go

Update the `paua-rc1` and `paua` upgrades to set the sanction module's params.
Immediate sanction and unsanction require a 1,000,000 hash deposit.
This PR also updates the `paua` (mainnet) upgrade to NOT increase the max gas per block. That increase is still in the `paua-rc1` upgrade though.
---

Update the paua upgrades to set the sanction params.

---

CHANGELOG.md
app/upgrades.go

Increase each validator's max commission change rate to 5% (if it's currently less than that).
Note: Even though this is technically being added to both `paua` and `paua-rc1` upgrades, it's unlikely that we will cut a new software `rc` before the `paua-rc1` upgrade is performed on `testnet`. That means that this change will not be applied to `testnet`, but will be applied during the `paua` upgrade on `mainnet`.
As of writing this, `testnet` has 6 validators. 5/6 of them have a max change rate of 100%. The other validator has a max change rate of 1% (`validator-us-west1-0`). But it's `testnet` and I figure we don't care that much about commission stuff on there.
---
checked off. If any of the checklist …

In paua, increase validators' commission max change rates to 5%

---

CHANGELOG.md
app/upgrades.go

Backport: #1360 to `release/v1.14.x`
---

Backport: In paua, increase validators' commission max change rates to 5% (#1360) to 1.14

---

CHANGELOG.md
cmd/provenanced/cmd/root.go
go.mod
go.sum

Backport #1371 to `release/v1.14.x`.
---

Backport: Bump Cosmos-SDK to v0.46.10-pio-1 (from v0.46.8-pio-3). (#1371) to 1.14

---

CHANGELOG.md
app/upgrades.go

Create the `paua-rc2` upgrade handler.
This will only be applied to `testnet` and does the following:
* Re-runs the validator commission updates to include the bump in max change rate.
* Undoes the max gas per block bump (putting it back at `60,000,000`).
---

Create paua-rc2 upgrade handler

---

.github/workflows/docker.yml
.github/workflows/proto.yml
.github/workflows/release.yml
.github/workflows/sims.yml
.github/workflows/test.yml
scripts/protoball.sh

closes: #1200 
Replace uses of the deprecated `set-output` github directive.
---

Replace set-output uses in github actions.

---

CHANGELOG.md
cmd/provenanced/config/manager.go

In the config manager, when loading a config map into viper, do not include the "home" field.
The Tendermint BaseConfig struct has this field:
```
RootDir string `mapstructure:"home"`
```
So when we convert a `tendermint.Config` into a field value map, it will have a "home" entry. The `DefaultConfig()` has it as `""`, and it's not a field in the tendermint config file. So it will almost always be `""`. Then, when we provide the field value map to viper, viper thinks, "I have been given `""` as the `"home"` value, so I don't need to use the default (defined with the command's flags)." Later, whenever anyone asks viper to `.Get(flags.FlagHome)`, an empty string is returned. 
I verified this by:
1. Adding some `fmt.Printf("home dir: \"%v\"\n", vpr.Get(flags.FlagHome))` lines before and after …

Ignore the home field when adding a config map to viper.

---

CHANGELOG.md
go.mod
go.sum

Bump Cosmos SDK to `v0.46.10-pio-2` to fix state listening `stopNodeOnErr`.
---

bump CosmosSDK to v0.46-10-pio-2

---

CHANGELOG.md
cmd/provenanced/config/manager.go

Backport of #1393 to `release/v1.14.x`.
---

Backport: Ignore the home field when adding a config map to viper. (#1393)

---

.gitignore
CHANGELOG.md
Makefile

Fixes the `make proto-gen` error:
```
$ make proto-gen
<snip>
go mod tidy
go: finding module for package github.com/btcsuite/btcd/btcec
github.com/provenance-io/provenance/x/metadata/types imports
github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.23.4), but does not contain package github.com/btcsuite/btcd/btcec
make: *** [proto-gen] Error 1
```
The `go.mod` file is being updated by the docker container that does the work. This PR updates the make target to back up `go.mod` first, then gen, then restore it before doing `go mod tidy`.
---

Fix make proto-gen

---

CHANGELOG.md
x/metadata/client/cli/cli_test.go
x/metadata/keeper/export_test.go
x/metadata/keeper/keeper.go
x/metadata/keeper/msg_server.go
x/metadata/keeper/record.go
x/metadata/keeper/scope.go
x/metadata/keeper/scope_test.go
x/metadata/keeper/session.go
x/metadata/keeper/session_test.go
x/metadata/keeper/signers.go
x/metadata/keeper/signers_test.go
x/metadata/keeper/signers_utils.go
x/metadata/keeper/signers_utils_test.go
x/metadata/spec/01_concepts.md

closes: #1280
This makes it so that, for metadata messages, if a smart contract is a signer, one of the following must be satisfied:
* They are a party/owner of the thing being written.
* All signers after it have granted authorizations (via authz) to it for the message type. The last signer cannot be a smart contract address unless they are a party/owner.
This also:
* Updates the non-rollup validation to enforce the provenance/smart-contract role.
* Fixes rollup provenance/smart-contract role validation to correctly look at the proposed parties.
---

Require smart contract signers to either be a party or be authorized by other signers.

---

go.mod
go.sum

Backport of #1477 to `release/v1.15.x`.
Bump wasmd to `v0.30.0-pio-2` (from `v0.30.0-pio-2-rc2`).
---

Bump wasmd to v0.30.0-pio-2 (from v0.30.0-pio-2-rc2). (#1477)

---

.github/workflows/release.yml

Bump `provenance-io/npm-publish-action` to `v1.1` (from `v1`).
---

Bump provenance-io/npm-publish-action to v1.1 (from v1).

---

CHANGELOG.md
app/params/weights.go
x/name/client/cli/cli_test.go
x/name/client/cli/tx.go
x/name/handler_test.go
x/name/keeper/msg_server.go
x/name/simulation/operations.go
x/name/simulation/operations_test.go
x/name/spec/03_messages.md

Allow name owner to execute msg modify name

---

.golangci.yml
CHANGELOG.md
app/prefix_test/prefix_test.go
app/upgrades.go
app/upgrades_test.go

Remove the `paua` and `paua-rc2` upgrades and stuff specific to those upgrades.
Add upgrade handlers for `rust-rc1` and `rust`. The `rust-rc1` upgrade will create a gov v1 `MsgSubmitProposal` message fee (if it doesn't already exist). Both upgrades will delete the `MsgP8eMemorializeContractRequest` message fee since that message no longer exists.
---

Add upgrade handlers for rust-rc1 and rust.

---

CHANGELOG.md
Makefile
RELEASE_CHANGELOG.md
internal/antewrapper/handler.go
internal/antewrapper/msg_blacklist.go
internal/antewrapper/msg_blacklist_test.go

Disallow some messages due to barberry.
Mark `v1.15.2` in the changelog.
This PR is only applied to `release/v1.15.x` as it won't be needed in `main`. `main` will get an updated SDK version with a better fix.
---

Disallow some messages and mark v1.15.2.

---

CHANGELOG.md
Makefile

This PR:
* Brings the `v1.15.2` and `v1.15.1` changelog entries into `main` from `release/v1.15.x`.
* Updates the `validate-go-version` make target to only allow version 1.20. This change was made in `release/v1.15.x` for `v1.15.2` but with go version 1.18. But since we're only going to support 1.20 for `v1.16`, it's a good change to have in `main` too. Currently, `main` just requires at least go version 1.17, which isn't correct anyway.
---

Mark v1.15.2 and v1.15.1 in the changelog. Update validate-go-version make target to only allow go version 1.20.

---

CHANGELOG.md
app/upgrades_test.go
cmd/provenanced/cmd/cmd_test.go
cmd/provenanced/cmd/config_test.go
cmd/provenanced/cmd/init.go
cmd/provenanced/cmd/pre_upgrade.go
cmd/provenanced/cmd/pre_upgrade_test.go
cmd/provenanced/cmd/root.go
cmd/provenanced/cmd/root_test.go
cmd/provenanced/config/interceptor.go
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go
cmd/provenanced/main.go
scripts/initialize.sh
x/attribute/simulation/operations_test.go
x/name/simulation/operations_test.go

This PR:
1. Creates the `provenanced pre-upgrade` command as outlined by cosmovisor documentation. It will update the config files to the new formats and set `consensus.timeout_commit` to 5 seconds.
2. Adds an error message to the log if the `consensus.timeout_commit` is too low.
3. Fixes an issue where the `minimum-gas-prices` value was being set to "" when either rewriting a packed config or calling `provenanced config pack` on an already packed config.
4. Fixes the `provenanced debug pubkey-raw` command that was trying to add a flag with a `-t` shorthand that conflicted with the `--testnet`/`-t` persistent flag on the root command.
---
checked off. If any of the checklist items are not applicable, …

Create pre-upgrade command. Fix minimum-gas-prices repacking unset.

---

CHANGELOG.md
app/upgrades_test.go
cmd/provenanced/cmd/cmd_test.go
cmd/provenanced/cmd/config_test.go
cmd/provenanced/cmd/init.go
cmd/provenanced/cmd/pre_upgrade.go
cmd/provenanced/cmd/pre_upgrade_test.go
cmd/provenanced/cmd/root.go
cmd/provenanced/config/interceptor.go
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go
cmd/provenanced/main.go
scripts/initialize.sh
x/attribute/simulation/operations_test.go
x/name/simulation/operations_test.go

Backport of #1594 to `release/v1.16.x`.
---

Backport: Create pre-upgrade command. Fix minimum-gas-prices repacking unset. (#1594)

---

CHANGELOG.md
cmd/provenanced/cmd/config_test.go
cmd/provenanced/cmd/pre_upgrade.go
cmd/provenanced/cmd/pre_upgrade_test.go
cmd/provenanced/cmd/root.go
cmd/provenanced/cmd/root_test.go
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go

* Change the default `consensus.timeout_commit` to `1500ms`.
* Make the `pre-upgrade` command always update the `consensus.timeout_commit` to `1500ms`.
* Change the `consensus.timeout_commit` log warning to only log about values being too large (more than `3500ms`).
---

Change the default consensus.timeout_commit to 1500ms.

---

CHANGELOG.md
cmd/provenanced/cmd/config_test.go
cmd/provenanced/cmd/pre_upgrade.go
cmd/provenanced/cmd/pre_upgrade_test.go
cmd/provenanced/cmd/root.go
cmd/provenanced/cmd/root_test.go
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go

Backport of #1600 to `release/v1.16.x`.
---

Backport: Change the default consensus.timeout_commit to 1500ms. (#1600)

---

.github/workflows/proto-registry.yml
protoBindings/bindings/java/build.gradle.kts
protoBindings/bindings/kotlin/build.gradle.kts
protoBindings/gradle.properties

* Publish the java/kotlin libraries using `provenanceio-bot` instead of a specific developer.
* When `buf.lock` needs updating, create the PR using `provenanceio-bot`.
---

Switch maven publishing and buf.lock PR creation to provenanceio-bot.

---

CHANGELOG.md
internal/provwasm/stargate_whitelist.go

This PR adds Trigger module query support for smart contracts
closes: #1636 
---

add Trigger module queries to stargate whitelist for smart contracts

---

CHANGELOG.md
app/app.go
x/marker/keeper/export_test.go
x/marker/keeper/keeper.go
x/marker/keeper/keeper_test.go
x/marker/keeper/marker.go
x/marker/keeper/proposal_handler_test.go
x/marker/keeper/send_restrictions.go
x/marker/keeper/send_restrictions_test.go
x/marker/simulation/proposals_test.go
x/marker/spec/03_messages.md
x/marker/spec/12_transfers.md
x/marker/spec/README.md
x/marker/types/immutable_addresses.go
x/marker/types/immutable_addresses_test.go

closes: #1626 
This PR fixes a bug related to quarantine of restricted coins, and also enables the use of restricted coins for other things that require an intermediary holding account. It also prevents forced transfers from module accounts.
Quarantine of restricted coins is fixed by adding a hard-coded list of addresses that bypass the required attributes checking. That list consists of the following module account addresses: 
- `authtypes.FeeCollectorName` - Allows paying fees with restricted coins.
- `reward` - Allows reward programs to use restricted coins.
- `quarantine` - Allows quarantine and acceptance of quarantined coins.
- `gov` - Allows deposits to have quarantined coins.
- `distribution` - Allows collection of delegation and fee rewards in restricted coins.
- …

Allow restricted coins to be quarantined

---

.github/workflows/changelog.yml
.github/workflows/lint.yml
.golangci.yml
CHANGELOG.md
contrib/devtools/Makefile

Add changelog entries for dependabot PRs.
closes: #1674 
---

Add dependabot changelog GHA hook

---

CHANGELOG.md
cmd/provenanced/config/manager.go
cmd/provenanced/config/manager_test.go

This updates the configuration load order so that custom.toml is the last. This allows any custom changes to overwrite anything that comes packed or unpacked config.
closes: #1262 
---

Change config load order so custom.toml is last

---

CHANGELOG.md
app/upgrades.go

Fix the saffron and saffron-rc1 upgrade handlers to add the correct store key for ibchooks.
---

Fix upgrade to add correct ibchooks key.

---

.github/workflows/changelog.yml

I also gave the `BOT_CPR_PAT` access to read/write workflows/actions. Hopefully this will cause the actions to be triggered on the dependabot changes after the changelog is updated.
---

Switch to a provenanceio-bot PAT for the dependabot changelog action.

---

CHANGELOG.md
RELEASE_CHANGELOG.md

Mark `v1.17.0-rc2` in the changelog and release notes.
I accidentally made this change directly to `release/v1.17.x` and pushed it up. Since we can't `push --force`, I then reverted it and pushed that up to get the branch back to where it was before. Then I created this branch with the change so it could be PRd and merged like it should be.
---

Mark v1.17.0-rc2 in the changelog and release notes.

---

CHANGELOG.md
app/upgrades.go
app/upgrades_test.go

Adds the upgrade handler for 1.18.
closes: #1755
---

Add 1.18 upgrade handler

---

CHANGELOG.md
cmd/provenanced/cmd/cmd_test.go
cmd/provenanced/cmd/root.go

Adds Osmosis' autocomplete generation command to the Provenance binary.
closes: #1687
---

Add auto complete.

---

x/README.md

Fix the module spec links in `x/README.md`.
---

Fix the module spec links in x/README.md.

---

CHANGELOG.md
go.mod
go.sum

Bump `github.com/CosmWasm/wasmvm` to v1.2.6 (from v1.2.4) to address [CWA-2023-004](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-004.md)
Closes: #1799 
---

Bump wasmvm to v1.2.6 (from v1.2.4).

---

CHANGELOG.md
app/store_loader.go
app/store_loader_test.go
cmd/provenanced/config/manager.go

This PR changes the default `iavl-disable-fastnode` value to `false` and the default `tx_index.indexer` value to `"null"`. It also allows the `tx_index.indexer` value to be either `""` or `"null"` without issuing a warning.
---

Change default iavl-disable-fastnode and indexer values.

---

CHANGELOG.md
app/store_loader.go
app/store_loader_test.go
cmd/provenanced/config/manager.go

This backports the `iavl-disable-fastnode` and `tx_index.indexer` defaults:
* #1807 
---

Backport: Change default iavl-disable-fastnode and indexer values: #1807.

---

CHANGELOG.md
app/app.go
app/store_loader.go
app/store_loader_test.go
app/test_helpers.go
app/upgrades_test.go
internal/logger.go
testutil/mocks/logger.go
x/attribute/keeper/genesis_test.go
x/exchange/keeper/suite_test.go

This PR primarily adds a check of the `PIO_ACKWARN` environment variable. If it exists, and isn't something false-like (i.e. `"0"`, `"f"`, '"F"`, `"false"`, `"False"`, or `"FALSE"`), the 30-second sleep is skipped after issuing the config warnings.
This PR also:
* Tweaks the wrapper a bit primarily to allow the tests to run without actually having to wait on the sleeps.
* Adds another log message with the sleep that says how to make the sleep go away, and moves the sleep messages to after the warnings.
* Definition of the default store loader is back in `app/app.go#New`. This made tests on the wrapper stuff easier since I could always use a mock store loader for them.
* Provides a standard way to create a logger that writes to a buffer. This makes it easier to test what has been logged. …

Allow bypassing the new warning wait period through PIO_ACKWARN env var.

---

CHANGELOG.md
app/app.go
app/store_loader.go
app/store_loader_test.go
app/test_helpers.go
app/upgrades_test.go
internal/logger.go
x/attribute/keeper/genesis_test.go
x/exchange/keeper/suite_test.go

This PR backports the `PIO_ACKWARN` change to `release/v1.17.x`:
* #1810 
---

Backport: Allow bypassing the new warning wait period through PIO_ACKWARN env var: #1810

---

CHANGELOG.md
x/exchange/keeper/grpc_query_test.go
x/exchange/keeper/market.go
x/exchange/keeper/market_test.go
x/exchange/spec/01_concepts.md

Before this PR, the buyer settlement fee ratios were only usable if they were evenly applicable to the bid order price.
After this PR, a buyer settlement fee ratio is applicable to a price as long as the ratio has the same price denom.
This allows more flexibility in both bid order price (chosen by a user) and the buyer settlement fee ratios (defined by a market).
If the ratio isn't evenly applicable to the given price, the result is rounded up.
For example, given the ratio `7peach:3fig', here's what the fee would be for various prices:
* `7peach` * `3fig`/`7peach` = `3fig`
* `12peach` * `3fig`/`7peach` =  5.14... => `6fig`
* `16peach` * `3fig`/`7peach` = 6.85... => `7fig`
Seller settlement fee ratios are already applied this way.
---
Before we can merge this PR, please make sure that all …

Allow bid order prices to not be evenly divisible by buyer settlement fee ratios.

---

CHANGELOG.md
RELEASE_CHANGELOG.md
app/app.go

This PR backports the following PR to `release/v1.18.x`:
* #1852 
---

Backport: 1852: Use the default store loader when an upgrade doesn't need a custom one.

---

CHANGELOG.md
x/exchange/client/cli/cli_test.go
x/exchange/client/cli/tx_test.go
x/marker/keeper/keeper.go
x/marker/keeper/keeper_test.go

This PR backports the following PR to `release/v1.18.x`:
* #1883
---

Backport: 1883 (Allow NAVs to have a greater volume than the marker's supply).

---

CHANGELOG.md
x/marker/client/cli/tx.go

Cherry-pick #1995 nav cli fix to release/v1.18.x.
closes: #XXXX
---

Cherry-pick NAV cli fix 

---

CHANGELOG.md
internal/provwasm/query_plugins.go

This PR backports the following PR to `release/v1.19.x`:
* #2083 
---

Backport: add grpc querier for wasm, #2083.

---

CHANGELOG.md
RELEASE_CHANGELOG.md
app/upgrades.go
app/upgrades_test.go

I accidentally put the upgrade proposal in for "umber-rc4" which doesn't exist. So we need this so we can start again.
This PR also marks `v1.19.0-rc5` in the changelog.
This is going to `release/v1.19.x` first so we can get unstuck faster.
---

Mark v1.19.0-rc5 and rename umber-rc2 to umber-rc4.

---

CHANGELOG.md
cmd/provenanced/cmd/root.go

This is a frontport of the following PR to `main`:
* #2108 
It updates the changelog to mark `v1.19.1` and fixes the mainnet queries.
---

Mark v1.19.1 and fix mainnet CLI queries.

---

.github/workflows/docker.yml

Use latest release of heighliner to fix CI process.
* supports go `1.23`
* fixes libwasm pathing bug
Closes #2185

fix(ci): heighliner build

---

.changelog/v1.20.0-rc2/bug-fixes/2182-fix-release-changelog.md
.changelog/v1.20.0-rc2/bug-fixes/2184-fix-heighliner.md
.changelog/v1.20.0-rc2/summary.md
CHANGELOG.md
RELEASE_CHANGELOG.md

This PR marks `v1.20.0-rc2` in the changelog and release changelog because `v1.20.0-rc1` had the release changelog named the wrong thing, so it didn't actually create the release.
---

Mark v1.20.0-rc2

---

.changelog/unreleased/bug-fixes/2189-remove-params-storekey.md
app/app.go

This PR backports the following to `release/v1.20.x`:
* #2189 
---

Backport: Remove the params store key and transient store key from the app: #2189.

---

.changelog/unreleased/features/2260-validator-commission-bumps.md
app/app.go
app/upgrades.go
app/upgrades_test.go

This PR creates the `wisteria-rc1` and `wisteria` upgrades and removes the `viridian` ones.
The wisteria upgrades will update the commission of all validators to be 60% with a max rate of 60%. It will also update the minimum rate (for any validator) to 60%.
---

Create the wisteria upgrade that update validator commissions.
