.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
* They were using 'master' branch instead of main.
closes: #XXXX
---
=> Updating links in PULL_REQUEST_TEMPLATE.md

proto/provenance/metadata/v1/tx.proto, x/attribute/module.go, x/metadata/client/cli/cli_test.go, x/metadata/client/cli/query.go, x/metadata/client/cli/tx.go, x/metadata/client/rest/grpc_query_test.go, x/metadata/handler.go, x/metadata/keeper/msg_server.go, x/metadata/keeper/scope.go, x/metadata/module.go, x/metadata/types/codec.go, x/metadata/types/msg.go, x/metadata/types/tx.pb.go
Added the cli client for adding and removing scopes.  Fixed various other issues along the way.
closes: #66
---
=> Metadata scope client

CHANGELOG.md, x/marker/legacy/v040/migrate.go, x/marker/legacy/v040/migrate_test.go
Implementation of the migrate accesslist function for v39 to v40 markers.
closes: #46
---
=> implement migrate access list for v39 marker

CHANGELOG.md, internal/legacy/v040/migrate.go, x/attribute/legacy/v039/types.go, x/attribute/legacy/v040/migrate.go, x/attribute/legacy/v040/migrate_test.go, x/attribute/legacy/v040/types.go
This  PR implements a migration function for the v039 account module into the v040 attribute module.
closes: #100 
---
=> implement migration for v039 account to v040 attribute

.github/workflows/matrix.yml, CHANGELOG.md, Makefile
=> Update makefile to include building zip, checksum, and plan

CHANGELOG.md
=> Release notes update to main for v0.1.5

app/app.go
Fix npe on startup when no plans exist.
=> Fix npe with startup and storeLoader

.github/workflows/cover.yml, CHANGELOG.md, x/metadata/legacy/v040/migrate_test.go, x/metadata/types/address.go, x/metadata/types/address_test.go, x/metadata/types/specification_test.go
Truncates sha256 hashes used in record and record specification metadata addresses.
closes: #132 
---
=> Truncate name sha256 in record, recordspec

CHANGELOG.md, app/upgrades/upgrades.go
=> Add new version for changelog entry

.github/workflows/matrix.yml, CHANGELOG.md, Makefile, scripts/protoball.sh
Create release artifact for protos.
closes: #69 
---
=> Add proto zip to release process

CHANGELOG.md, app/app.go, go.mod, go.sum
Updates provenance to use cosmos SDK 0.42
closes: #141 
---
=> update dependencies for 0.42 sdk release

.github/workflows/docker.yml, CHANGELOG.md, RELEASE_CHANGELOG.md, app/upgrades/upgrades.go, docker/blockchain/Dockerfile
=> #156 - Add docker xbuild github action

docker/blockchain/Dockerfile
=> Make sure proper ports are exposed

app/app.go, app/upgrades.go, app/upgrades/upgrades.go, cmd/provenanced/cmd/addresses.go, cmd/provenanced/cmd/addresses_test.go
=> Enhance upgrade handlers and add 0.2.1 upgrade handler.

app/upgrades.go
Replace 0.2.1 handler with 0.2.2 since 0.2.1 has not run yet.
closes: #XXXX
---
=> Due to halted chain, 0.2.1 has not run yet.

.dockerignore, .github/workflows/docker.yml, .github/workflows/matrix.yml, Makefile, docker/blockchain/Dockerfile
Fix the versioning in docker and native binaries.
Build docker image using same make target as native binaries to ensure version args get passed in to `go build`.
---
=> Fix versioning in binary, docker, and others; to reference new VERISON string in makefile.

networks/local/blockchain-local/Dockerfile, networks/local/docker-compose.yml
Exposes default gRPC port 9090 for local development
closes: #XXXX
---
=> Expose default gRPC port 9090 on localnet

CHANGELOG.md, go.mod, go.sum
Updates cosmos sdk dependency to 0.42.2
closes: #182 
---
=> update cosmos sdk dependency

CHANGELOG.md
Add a changelog line that was forgotten in the main PR: #165 
closes: #164 
---
=> [164]: Add changelog entry.

CHANGELOG.md, app/upgrades.go
=> v0.3.0 main sync

CHANGELOG.md, x/metadata/client/cli/cli_test.go, x/metadata/client/cli/tx.go, x/metadata/types/msg.go
Add cli command for Add/Update/Remove operations on `ScopeSpecification`
closes: #202 
---
=> Cli scope specification

CHANGELOG.md, go.mod, go.sum
Updates cosmos sdk dependency to 0.42.3.
closes: #204 
---
=> Update cosmos sdk to 0.42.3

app/export.go, x/name/simulation/genesis.go
Updated export flow based on latest work in the SDK.
closes: #215 
---
=> update export to handle empty delegation rewards

CHANGELOG.md
=> 1.0.0 release sync

app/app.go, internal/statesync/statesync.go
Add tendermint rpc (port 26657) endpoint for fetching sync info (version, hash, height).
---
=> Add jsonrpc endpoint to fetch state sync information

docker/README.md
=> Add simple docker readme with transaction example.

CHANGELOG.md, x/metadata/keeper/keeper.go, x/metadata/keeper/msg_server.go, x/metadata/keeper/objectstore.go, x/metadata/types/keys.go
* Change OSLocatorExists to take in an AccAddress instead of a string. This matches the signature of the other keeper functions.
* Remove double setting of OSL entries as two separate entries. The second entry wasn't needed.
* Clean up DeleteRecord to be more efficient.
* Update ModifyRecord to just write over the existing record.
* Change name of GetOsLocatorAddressKeyPrefix to GetOSLocatorKey to better match the other key generation funcs.
---
=> Remove extra Object Store Locator storage.

Makefile
Add cgo ldflags to make the binary look in pwd for the libwasmvm.so
---
=> Add rpath lookup for pwd libwasmvm

CHANGELOG.md, Makefile
=> Cherry picked commit for rpath to release branch

x/marker/types/codec.go
Add MsgSetDenomMetadataRequest and WithdrawEscrowProposal types to the marker codec.
---
=> Add MsgSetDenomMetadataRequest and WithdrawEscrowProposal to the marker codec.

CHANGELOG.md, app/upgrades.go
Update change log after version v.1.1.0 release
closes: #XXXX
---
=> Update changelog v1.1.0

CHANGELOG.md, app/app.go, cmd/provenanced/cmd/root.go, x/marker/client/cli/cli_test.go, x/marker/handler_test.go, x/marker/legacy/v040/migrate_test.go, x/marker/types/denom.go, x/marker/types/denom_test.go, x/marker/types/params.go, x/marker/types/params_test.go
Updated regex checks on denom to not allow slashes.
closes: #258 
---
=> Disallow slashes in denom

app/upgrades.go
Adds a release plan for use with v1.2.0 upgrades (testnet)
closes: #268 
---
=> Release plan amaranth

CHANGELOG.md
Merge v1.2.x into main.  This will update the change log.
closes: #XXXX
---
=> Merge v1.2.x into main

CHANGELOG.md, CONTRIBUTING.md, scripts/linkify.py
* Added script and ran it against the change log
closes: #107
---
=> Linkify CHANGELOG

CHANGELOG.md, x/attribute/handler.go, x/attribute/handler_test.go, x/marker/handler.go, x/marker/handler_test.go, x/metadata/handler.go, x/name/handler.go, x/name/handler_test.go
Updates each modules handler to setup a new event manager scope within the handler function that processes msgs.  Modifies unit tests to assert on the response from the handler to check for events.
closes: #288 
---
=> Update module event handler scope

CHANGELOG.md, README.md, x/marker/keeper/keeper_test.go, x/marker/keeper/marker.go, x/marker/spec/01_state.md, x/marker/spec/02_state_transistions.md, x/marker/spec/02_state_transitions.md, x/marker/spec/03_messages.md, x/marker/spec/04_begin_block.md, x/marker/spec/05_end_block.md, x/marker/spec/06_hooks.md, x/marker/spec/07_events.md, x/marker/spec/08_telemetry.md, x/marker/spec/09_params.md, x/marker/spec/10_governance.md, x/marker/spec/README.md
Documentation for the marker module.
closes: #93 
closes: #303 
---
=> Marker module spec documentation

CHANGELOG.md, x/marker/abci.go, x/marker/keeper/marker.go
- Changes logging levels in normal circulation adjustment to info from error.
- Adds error logging message to ABCI supply check/adjustment
- Adds defer telemetry measurement to ABCI begin block method of marker module.
closes: #318 
---
=> Adjust logging levels in marker mint/burn

CHANGELOG.md, Makefile, cmd/provenanced/cmd/init.go, cmd/provenanced/cmd/root.go, cmd/provenanced/cmd/testnet.go
Adds defaults for min-gas-price and validation to ensure it is set correctly.
closes: #310 
---
=> Minimum gas price validation for mainnet

CHANGELOG.md, x/marker/spec/07_events.md, x/marker/types/events.go
Updated spec documentation for marker events to match typed event updates.
closes: #304 
---
=> Update marker event spec documentation

CHANGELOG.md, app/upgrades.go
Update upgrade handler for version `citrine`
closes: #339
---
=> Add empty upgrade handler for version citrine

.github/workflows/release.yml
During testing, the body was referenced as the string "Testing". This PR properly updates the action to be able to pull in the RELEASE_CHANGELOG.md from the source tree.
---
=> Need to check out the code now that we are referencing RELEASE_CHANGELOG.md

CHANGELOG.md, go.mod, go.sum, networks/local/blockchain-local/Dockerfile
The PR bumps `wasmd` to v0.17.0.  All `provwasm` integration tests pass.
closes: #345 
---
=> wasmd v0.17.0

CHANGELOG.md, x/name/handler_test.go, x/name/keeper/keeper.go, x/name/keeper/msg_server.go, x/name/types/events.go
Align name module events with marker module convention where typed events are emitted from the keeper.
closes: #267 
---
=> 267 refactor name module events

.github/workflows/lint.yml, .golangci.yml, CHANGELOG.md, go.mod, go.sum, internal/antewrapper/tracing_meter.go, internal/antewrapper/tracing_meter_test.go
Updates Cosmos SDK to 0.42.6 with Tendermint 0.34.11.
closes: #355 
---
=> update to cosmos sdk 0.42.6

CHANGELOG.md, x/metadata/keeper/scope.go, x/metadata/keeper/scope_test.go, x/metadata/types/specification.go, x/metadata/types/specification_test.go
Allows delegated value ownership to be maintained without existing scope owner signatures.
closes: #347 
---
=> Scope value owner update without scope owner signatures

CHANGELOG.md, x/marker/client/cli/query.go
Removed the cast to lower case for marker query command.
closes: #329 
---
=> Remove lowercase casting of marker in cli query

app/upgrades.go
Adds upgrade handler for release `desert`
closes: #361 
---
=> Add empty upgrade handler for release 'desert'

CHANGELOG.md, proto/provenance/marker/v1/proposals.proto, x/marker/client/cli/cli_test.go, x/marker/client/cli/tx.go, x/marker/keeper/proposal_handler.go, x/marker/types/msg.go, x/marker/types/proposal.go, x/marker/types/proposals.pb.go, x/marker/types/proposals_test.go
- Adds cli method to the marker module to create governance proposals for the various marker proposals.
- Add cli unit testing of marker governance proposals
- Registers WithdrawEscrow marker governance proposal (previously not properly linked to gov module)
- Fixes 'adddress' spelling error in Marker Withdraw Escrow proposal and IncreaseSupply proposal (optional field).  Neither of these governance proposals have been used.  The Withdraw Escrow proposal could not be used as it was not wired in.
closes: #367 
---
=> Initial marker gov proposal cli support

x/metadata/handler_test.go, x/metadata/keeper/record_test.go, x/metadata/keeper/specification_test.go, x/metadata/types/metadata_test.go, x/metadata/types/oslocatorparams_test.go, x/metadata/types/p8e_test.go
Apply `gofmt -s` to a handful of unit tests files that still needed it. Now, `make lint` doesn't complain about anything anymore.
---
=> Apply gofmt to the test files that still need it

CHANGELOG.md, Makefile, client/docs/swagger-ui/swagger.yaml, third_party/proto/cosmos/base/query/v1beta1/pagination.proto, third_party/proto/tendermint/abci/types.proto
As part of updating to 0.43 of the Cosmos SDK the third party proto definitions also should be reviewed and updated as needed
The third party proto files are stored in the provenance repository as canonical versions for build dependencies.  These files are managed using a `make proto-update-deps` target.  The referenced sources must be updated when the SDK is updated.
closes: #391 
---
=> Update third party proto files

CHANGELOG.md, x/metadata/handler_test.go, x/metadata/keeper/msg_server.go, x/metadata/types/msg.go, x/metadata/types/scope.go, x/metadata/types/specification.go, x/name/types/proposal.go
Fix the receivers on the ValidateBasic funcs.
closes: #412
---
=> Fix receivers on ValidateBasic funcs.

CHANGELOG.md, client/rosetta/rosetta-ci/Dockerfile, docker/blockchain/Dockerfile, go.mod, go.sum, networks/local/blockchain-local/Dockerfile
Add updated version of provenance forked wasmd to with updated support for cosmos-sdk v0.43.0
closes: #409 
---
=> Add wasmd v0.19.0-alpha

.gitignore, CHANGELOG.md, x/marker/client/cli/tx.go
* Fix cli `marker new` example output
closes: #415 
---
=> Cli marker new example is incorrect

.github/workflows/docker.yml, .github/workflows/sims.yml, .github/workflows/test.yml, CHANGELOG.md, README.md, client/rosetta/rosetta-ci/Dockerfile, docker/blockchain/Dockerfile, docker/gateway/Dockerfile, go.mod, networks/local/blockchain-local/Dockerfile
Update to go 1.17 for cpu and memory utilization improvements.
closes: #454 
---
=> Switch from go version 1.16 to 1.17

.gitignore, CHANGELOG.md, client/rosetta/configuration/bootstrap.json, x/metadata/client/cli/query.go, x/metadata/client/cli/tx.go
Update some example addresses to use our prefix.
closes: #453 
---
=> Update some example addresses to be for our chain.

app/upgrades.go
Upgrade handler's wasm permissions restrictions was applied to wrong network.  It has been fixed from testnet to mainnet.
closes: #461 
---
=> wasm restriction upgrade handler change from testnet to mainnet

x/marker/client/cli/query.go
Error while executing `marker holding` query due to improper setting of pagination flags.
closes: #465 
---
=> CLI Marker holders command error with page-key message

.github/workflows/release.yml
Use go version 1.17 for the release workflows. That's what the others use, and having it at 1.15 makes it not work because `go.mod` asks for `1.17`.
---
=> Update the release workflows go version to 1.17

.github/workflows/release.yml, CHANGELOG.md
Release v1.7.x merge to main
closes: #XXXX
---
=> Add v1.7.0 changelog entry

CHANGELOG.md, Makefile, networks/dev/README.md, networks/dev/blockchain-dev/Dockerfile, networks/dev/blockchain-dev/entrypoint.sh, networks/dev/docker-compose.yml, networks/dev/mnemonics/account-1.txt, networks/dev/mnemonics/account-2.txt, networks/dev/mnemonics/validator.txt
Added a single node docker based development environment.
closes: #311
---
=> Local development improvement

CHANGELOG.md, x/metadata/spec/02_state.md, x/metadata/types/keys.go
Update the documented type bytes used by some of the Metadata indexes.
closes: #474
---
=> Update some Metadata documentation on indexes

CHANGELOG.md, x/marker/keeper/genesis.go, x/marker/keeper/marker.go, x/marker/keeper/proposal_handler.go
Add validation call before setting marker to prevent panics.
closes: #491 
---
=> Ensure marker state transition validation not panic

CHANGELOG.md, app/upgrades.go, x/attribute/keeper/migrations.go, x/attribute/legacy/v042/store.go, x/marker/keeper/migrations.go, x/marker/legacy/v042/store.go, x/metadata/keeper/migrations.go, x/metadata/legacy/v042/store.go, x/name/keeper/migrations.go
Fixed marker permissions migration to not use `Clone` method.
Add panic for `eigengrau` upgrade.
closes: #484 
---
=> 484 marker permission migration error on eigengrau upgrade

CHANGELOG.md, x/marker/keeper/genesis.go, x/marker/keeper/marker.go, x/marker/keeper/proposal_handler.go
Cherry pick changes from 491 into release v1.7.x branch.
closes: #491 
---
=> Cherry pick issue 492 marker validation changes to v1.7.x

.github/workflows/rosetta.yml, CHANGELOG.md
=> Increase timeout for rosetta tests

CHANGELOG.md, x/marker/keeper/keeper_test.go, x/marker/keeper/marker.go
Resolves potential denial of service finding where funds are sent to marker addresses before they can be created locking the denomination.
closes: #520 
---
=> Allow marker creation over existing accounts

CHANGELOG.md, x/marker/keeper/keeper_test.go, x/marker/keeper/marker.go
Updates logic to allow a marker manager to continue to refine grants on a finalized marker.
closes: #545
---
=> Allow finalized marker manager to modify grants

go.mod, go.sum, internal/antewrapper/fee_gas_meter.go, internal/antewrapper/msgbased_fee_decorator.go, internal/antewrapper/msgbased_fee_decorator_test.go, internal/antewrapper/prov_fee_test.go, internal/antewrapper/prov_feegrant_test.go, internal/antewrapper/provenance_fee.go, internal/handlers/msg_service_router_test.go, internal/handlers/pio_msg_fee_invoker.go, internal/handlers/pio_msg_fee_invoker_test.go
=> prevent double charge on fee charged via authz/cosmwasm.

CHANGELOG.md, RELEASE_CHANGELOG.md
=> v1.7.6 updates

.github/workflows/build-and-publish-proto-bindings.yml
Add GitHub action from main branch used to publish proto artifacts to nexus.
---
=> Copy GitHub action for publishing

CHANGELOG.md
This adds the changelog from `v1.7.6` to main.
---
=> Changelog update for 1.7.6

CHANGELOG.md, x/metadata/handler_test.go, x/metadata/keeper/migrations.go, x/metadata/keeper/migrations_test.go, x/metadata/keeper/msg_server.go
* When a record is updated and the session id is changed, check if the old session is now empty, and delete it if it is.
* Add a migration to delete empty sessions.
closes: #480 
---
=> Delete empty sessions when updating records to new session.

CHANGELOG.md, scripts/protoball.sh
Updated `./scripts/protoball.sh` to capture all included proto files into release zip.
closes: #556 
---
=> Capture all included protobufs into release zip

app/upgrades.go, app/upgrades_test.go
=> Upgrade with new msg based fees

CHANGELOG.md, app/app.go, x/metadata/wasm/encode.go, x/metadata/wasm/types.go
This PR adds metadata mutation support for Smart Contracts. It uses the `WriteScopeRequest` which contains the `Scope` type on the core side, and the respective type in provwasm for the Smart Contracts. All fields within the Scope type are available for modification following the current rules and restrictions.
closes: #531 
---
=> metadata mutation via wasm smart contracts support

.github/workflows/build-and-publish-proto-bindings.yml, CHANGELOG.md
=> add java distribution

.github/workflows/build-and-publish-proto-bindings.yml, CHANGELOG.md
* add java distribution
* update changelog
Backport #624 
closes: #XXXX
---
=> add java distribution (#625)

x/attribute/types/attribute_test.go
=> Fix message breaking unit test

CHANGELOG.md, app/upgrades.go
Updates the green upgrade handler with an additional msg fee.  Increases app gov proposal deposit requirement.
closes: #632 
---
=> Update gov module deposit requirements and add msg fee

CHANGELOG.md, app/upgrades.go
`green` upgrade handler was missing the declaration of new store `msgfees`.  This prevented the iavl version for msgfees not to be set to the current height.
closes: #XXXX
---
=> Add msgfees module to added store upgrades

.github/workflows/release.yml
backport `build_init` fix for maven publish
closes: #XXXX
---
=> add needs: build_init (#646)

.github/workflows/release.yml, CHANGELOG.md
=> Fix maven publish release version reference

.github/workflows/release.yml, CHANGELOG.md
remove "v" from jar artifact. Example `proto-java-v1.8.0.jar` => `proto-java-1.8.0.jar`
closes: #653 
---
=> remove v from artifact version

app/upgrades.go
=> new upgrade handler hazel.

.github/workflows/release.yml, CHANGELOG.md
* remove v from artifact version
* update changelog
backport [c31c926d891abf36a5608d914e5989cc372cd2f6](https://github.com/provenance-io/provenance/commit/c31c926d891abf36a5608d914e5989cc372cd2f6)
closes: #XXXX
---
=> backport - remove v from artifact version (#654)

app/upgrades.go
=> adding upgrade handler indigo.

CHANGELOG.md, app/test_helpers.go, app/upgrades.go, cmd/provenanced/cmd/init.go, cmd/provenanced/cmd/testnet.go, internal/antewrapper/handler.go, internal/antewrapper/tx_gas_limit_decorator.go
Backport of #681 to 1.8.x
closes: #XXXX
---
=> backport tx gas limits #681

x/metadata/wasm/types.go
backport of fix #676 to `1.8.x` release
---
=> backport: fix owner array initialization size when creating scope mutation wasm msg

app/upgrades.go, internal/antewrapper/tx_gas_limit_decorator.go
Adds `jasmine` upgrade handler and cherry picks updates from the following PR
https://github.com/provenance-io/provenance/pull/711
closes: #XXXX
---
=> Add jasmine upgrade handler

RELEASE_CHANGELOG.md
Fix release changelog summary.
---
=> Add summary to release changelog

CHANGELOG.md
Update the changelog to reflect the 1.8.0 release.
---
=> Update the CHANGELOG in main to reflect the 1.8.0 release.

.github/workflows/release.yml, CHANGELOG.md
If a tag is a release candidate (e.g. `v1.8.0-rc3`), set `prerelease` to `true`.
closes: #666 
---
=> Properly set the prerelease flag for release candidates.

x/name/client/cli/query.go
This is a minor correction to the help text for the query name lookup command.
closes: #757
---
=> Fixed typo in the query name lookup text.

x/metadata/client/cli/tx.go
Not all of the examples for the metadata subcommand are correct. One example that is wrong is the write-scope-specification. I've updated the examples to correctly match the required arguments.
closes: #680 
---
=> Updated Metadata examples

CHANGELOG.md, cmd/provenanced/cmd/config.go
Adds a home subcommand to the cli's config command. This outputs the home directory of provenanced.
closes: #620 
---
=> Add home subcommand to config

internal/antewrapper/tx_gas_limit_decorator.go
Previously gas limits were only bypassed for governance proposal submissions. They should also be bypassed for other governance messages such as voting and depositing.
closes: #789
---
=> Bypass gas limit for all governance transaction messages

CHANGELOG.md, app/app.go, app/sim_test.go, docker/blockchain/Dockerfile, go.mod, networks/local/kafka/docker-compose.yml, scripts/download_smart_contracts.sh, sims-state-listening.mk, sims.mk
Pulls the ADR-038 fixes from `main` into `release/v1.8.x`.
closes: #XXXX
---
=> Include ADR-038 fixes in 1.8.x

CHANGELOG.md
Update changelog to include summary and feature list.
closes: #XXXX
---
=> add changelog entries for 1.8.2

go.mod, go.sum
Bump the `wasmd` module to 26.0 (from 24.0) to fix a thing.
---
=> Bump wasmd to 26.0

CHANGELOG.md, app/upgrades.go
Adds the (empty) 1.9.x upgrade handler and updates the changelog to reflect the release.
---
=> Update changelog from v1.9.0 release.

Makefile, client/rosetta/rosetta-ci/Dockerfile, docker/blockchain/Dockerfile, go.mod, go.sum, networks/dev/blockchain-dev/Dockerfile, networks/local/blockchain-local/Dockerfile, networks/local/blockchain-local/entrypoint.sh
The go.mod file was updated to use the latest version of wasmvm. The main reason for this update is to get the prebuilt aarch64 wasmvm libraries, which are needed by our localnet Dockerfile. Additionally, the Dockerfile was updated to incorporate these new libraries.
A M1 kafka issue was found, and a fix was added to install the needed dependencies on M1 machines.
closes: #817 
---
=> Update wasmvm dependencies and update Dockerfile for localnet

x/metadata/keeper/query_server.go
The command `provenanced/ q metadata locator all` generates an error when no records exist. The module was updated to no longer display the error. It will instead output an empty list.
```
provenanced q metadata locator all
locators: []
pagination:
next_key: null
total: "0"
request: null
```
closes: #622 
---
=> Empty Object Locator list

CHANGELOG.md
Add changelog for v1.10.0
closes: #XXXX
---
=> Add changelog for v1.10.0

.github/CODEOWNERS
The purpose of this PR is to update the .github/CODEOWNERS file to include Carlton Hanna. There was no issue created for this.
There will be a later PR to remove Carlton Hanna's figure github from code owners.
closes: #XXXX
---
=> Add channa-figure personal github to code owners 

.github/CODEOWNERS
=> Add new id to code owners

CHANGELOG.md
Forgot to add changelog entries for #850. This corrects that.
---
=> Update changelog for changes that were in PR 850.

x/attribute/wasm/encode.go
This PR will add Update and DeleteDistinct functionality via wasm to the attribute module.
closes: #857 
---
=> Add Update and DeleteDistinct attribute message types to wasm in attribute module

CHANGELOG.md, app/upgrades.go, internal/handlers/msg_fee_handler.go, internal/handlers/msg_fee_invoker.go
Minor fixes needed for the `v1.11.1-rc1` release including:
* Add `mango` upgrade handler
* Fix minor lint errors
* Update changelog with incremented version info
---
=> Add upgrade handler. Fix lint errors. Update changelog version.

CHANGELOG.md, app/upgrades.go, internal/handlers/msg_fee_handler.go, internal/handlers/msg_fee_invoker.go
This cherry-picks the commits from #863 into the `release/v1.11.x` branch.
---
=> Cherry pick the lint and changelog updates into 1.11.x

RELEASE_CHANGELOG.md
Prepare release candidate: v1.11.1-rc1
closes: #XXXX
---
=> Release v1.11.1-rc1

CHANGELOG.md, docs/state-sync.md
Added node initialization steps.
closes: #869 
---
=> add initialization steps

CHANGELOG.md, app/upgrades.go, app/upgrades_test.go, internal/handlers/msg_service_router_test.go, x/msgfees/keeper/keeper_test.go, x/msgfees/types/params.go
Ensure new NhashPerUsdMil is set in the param space on upgrade.
Clean up unused upgrade method and tests.
closes: #XXXX
---
=> Add new param setting in upgrade handler 

CHANGELOG.md, app/upgrades.go, app/upgrades_test.go, internal/handlers/msg_service_router_test.go, x/msgfees/keeper/keeper_test.go, x/msgfees/types/params.go
* Add new upgrade handler, Clean up unused upgrade method and tests
* Add changelog
* Upgrade comment
* Update nhash per usd for 0.04 hash price
(cherry picked from commit acbe65661fc888e5d5092b8fbc1327ef006c0397)
closes: #XXXX
---
=> Add new param setting in upgrade handler  (#875)

scripts/estimate-block-height.sh
Adds the estimate-block-height script that is being used by multiple people.
closes: #886
---
=> Added estimate-block-height script

CHANGELOG.md
Adds changelog header for `release/v1.11.1-rc2`
closes: #XXXX
---
=> Add changelog header for v1.11.1-rc2

RELEASE_CHANGELOG.md
Add release changelog.
closes: #XXXX
---
=> add release changelog

CHANGELOG.md, app/upgrades.go
Create a `mango-rc4` upgrade handler to run the module migrations.
This PR is to update the `release/v1.11.x` branch. The PR to make the similar change to `main` is #896.
---
=> Add mango-rc4 hanlder

.github/workflows/release.yml, CHANGELOG.md, app/upgrades.go
This PR is currently just to get a run of the release workflow so we have something to test our credentials with.
For some reason, github didn't fire off the checks when it was in Draft, but it's not a PR that's ready to be merged.
---
=> Clean up the Mango RC upgrade handlers.

scripts/linux_arm64_librdkafka_install.sh
This fixes a permissions issue that was not encountered while testing. My docker image was initially using root, and I forgot about permissions. The `make install` command now contains sudo, and it will prompt the user for their password. This gives the proper permissions and allows librdkafka to correctly be installed.
closes: #941
---
=> Updated script with sudo.

CHANGELOG.md, app/app.go, app/sim_test.go, go.mod, go.sum, sims-state-listening.mk, third_party/proto/cosmos/authz/v1beta1/authz.proto
- Removes ADR 038 plugin system implementation from Provenance. 
- Bumps Cosmos SDK version to `v0.45.5-pio-1` from `v0.45.4-pio-4` which removes ADR 038 plugin system from SDK.
closes: #983 
---
=> Remove adr 038 plugin system

x/reward/types/reward.go, x/reward/types/reward_test.go
Adds unit tests for rewards.IsEndingClaimPeriod()
-->
closes: #XXXX
---
=> Add unit tests for IsEndingClaimPeriod

CHANGELOG.md, docs/grpcurl.md
=> add grpcurl docs

CHANGELOG.md
Add entry for the `Fix fee charging to sweep remaining fees on successful transaction` to state machine breaking change log section
closes: #XXXX
---
=> Add state machine breaking entry for 1019 fix

x/reward/types/reward.go, x/reward/types/reward_test.go
making min rollover amount to be 10% of claim distribution amount.
closes: #XXXX
---
=> making min rollover amount to be 10% of claim distribution amount.

CHANGELOG.md, app/upgrades.go
* Add v1.12.0 section for release changelog
* Add neoncarrot-rc1 upgrade handler
closes: #XXXX
---
=> Add artifacts for v1.12.0 release (#1030)

app/test_helpers.go, go.mod, x/marker/keeper/marker.go, x/marker/types/msg.go, x/marker/types/proposal.go
This removes the deprecated sdk.Int and replaces it with the new Int type in cosmosmath.
closes: #1012
---
=> Removed deprecated sdk.Int.

x/reward/client/cli/tx.go
Makes the `provenanced tx reward add-reward-program --help` example accurate.
The old version had the following problems:
1. The `--start-time` didn't have the right format (missing the time and zone).
2. The `--qualifying-actions` needed to be single-quoted. Without those, the whole thing is interpreted/expanded by the shell which does unexpected things resulting in an error that 2 arguments are expected, but 9 were received.
3. Changed the `maximum_delegation_amount` to 1 since it cannot be 0.
After this, you can copy/paste the command, add the `--from <addr>` and `--generate-only` and get the generated `tx` JSON.
Because I found it interesting, here's what the json expanded to:
```
> printf '[%s]\n' {"qualifying_actions":[{"delegate":{"minimum_actions":"0","maximum_actions":"0","minimum …
```
=> Fix the CLI add-reward-program example.

CHANGELOG.md, go.mod, go.sum
This PR includes the change to update ibc-go from v5.0.0 to v5.0.0-pio. This is a fork containing our changes to update the transfer module. The transfer module will now verify the coin has SendEnabled.
closes: #1100 
---
=> Updated ibc v5.0.0 to v5.0.0-pio

README.md
I noticed the cosmos-sdk link on the readme was 404'ing. I believe this is equivalent intro doc.
---
=> Fix broken cosmos-sdk doc url

CHANGELOG.md
With v1.12.1, the only changes needed aren't needed/wanted in main or 1.13. So all we need to do is update the changelog to include that entry.
---
=> Copy the v1.12.1 section into the changelog.

CHANGELOG.md, go.mod, go.sum
This applies the following PRs to release/v1.13.x:
- #1148 
Related to: https://github.com/provenance-io/provenance/issues/1149
---
=> Backport 1.13: wasmd bump.

CHANGELOG.md, RELEASE_CHANGELOG.md
Add the `v1.13.0-rc2` header to the changelog and update the release changelog to also include the `v1.13.0-rc2` info.
---
=> Add v1.13.0-rc2 header to the changelog and update the release changelog.

CHANGELOG.md, cmd/provenanced/cmd/root.go
This applies the following PRs to release/v1.13.x:
* #1193
---
=> Backport 1.13: Allow IAVL Disable Fastnode config option

CHANGELOG.md, RELEASE_CHANGELOG.md
Update the changelog and release changelog for v1.12.2.
---
=> Update changelog and release changelog for v1.12.2.

CHANGELOG.md, RELEASE_CHANGELOG.md
Update the changelog with the `v1.13.0-rc3` section and add that section to the release changelog.
---
=> Update changelog for v1.13.0-rc3

CHANGELOG.md
This PR updates the changelog on `main` to reflect the `v1.12.2` release.
---
=> Copy the 1.12.2 release changelog into the main changelog.

CHANGELOG.md, RELEASE_CHANGELOG.md, go.mod, go.sum
This applies the following PRs to release/v1.13.x:
* #1211 
It also updates the release changelog accordingly (since it wasn't actually released yet).
---
=> Backport 1.13: Bump Cosmos-SDK to v0.46.3-pio-4

x/name/legacy/v042/types.go
Fix incorrect name used in comment.
closes: #XXXX
---
=> Fix incorrect name used in comment

x/expiration/spec/01_concepts.md, x/expiration/spec/02_state.md, x/expiration/spec/03_messages.md, x/expiration/spec/04_authz.md, x/expiration/spec/05_events.md, x/expiration/spec/06_queries.md
=> Add expiration module specs

.github/workflows/release.yml, CHANGELOG.md
=> Enable RC publishing to maven

.github/workflows/release.yml, CHANGELOG.md
backport #1224 to v1.13.x
closes: #XXXX
---
=> 1224 backport to v1.13.x

CHANGELOG.md, app/upgrades.go, x/msgfees/keeper/params.go
Adds `ConversionFeeDenom` to get params and adds required setting in the upgrade handler for `ochre`
closes: #XXXX
---
=> Fix GetParams in `msgfees` modules to return ConversionFeeDenom (#1215)

CHANGELOG.md
Update the changelog to reflect v1.13.0-rc4 (and also v1.13.0-rc3).
---
=> Update the changelog to reflect v1.13.0-rc4

CHANGELOG.md, cmd/provenanced/cmd/config.go, cmd/provenanced/cmd/config_test.go, cmd/provenanced/config/manager.go, cmd/provenanced/config/manager_test.go, cmd/provenanced/config/reflector.go, cmd/provenanced/config/reflector_test.go
This applies the following PR to `release/v1.13.x`:
* #1233 
---
=> Backport 1.13: Config update command #1233

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark v1.13.0-rc5 in the changelog and release changelog.
---
=> Mark v1.13.0-rc5 in the changelog and release changelog.

CHANGELOG.md
=> updating changelog.

CHANGELOG.md, x/msgfees/spec/01_concepts.md, x/msgfees/spec/README.md
This will add assess msg fee documentation to the concepts section and add a link to the messages file in the README.md.  Not having these two elements had caused some confusion.
closes: #1172 
---
=> Add assess msg fee documentation to spec

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark v1.13.1 in the changelog and release notes.
---
=> Mark v1.13.1 in the changelog and release notes.

CHANGELOG.md
Update the changelog in `main` to include `v1.14.0-rc1`.
---
=> Update changelog for v1.14.0-rc1.

CHANGELOG.md
Copy the [v1.13.1 changelog section](https://github.com/provenance-io/provenance/blob/release/v1.13.x/CHANGELOG.md?plain=1#L44-L54) from `release/v1.13.x` into `main`
---
=> Add the 1.13.1 section to the changelog.

app/upgrades.go
Backport #1345 to `release/v1.14.x` to update the `paua-rc1` and `paua` upgrades to set the sanction params.
---
=> Backport: Update the paua upgrades to set the sanction params. (#1345) to v1.14.x

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.14.0-rc2` in the changelog and release changelog.
Related: #1354
---
=> Mark v1.14.0-rc2 in the changelog and release changelog.

.github/workflows/release.yml, CHANGELOG.md
Backport of #1367 to `release/v1.14.x`.
---
=> Backport: Remove mac binary release artifact. (#1367)

CHANGELOG.md, app/app.go
Backport of #1356 to `release/v1.14.x`
---
=> Backport: log streaming plugin loading errors with app.logger (#1356) to 1.14

CHANGELOG.md, app/upgrades.go
Backport #1373 to `release/v1.14.x`.
---
=> Backport: Create paua-rc2 upgrade handler (#1373) to 1.14

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.14.0-rc3` in the changelog and release notes.
---
=> Mark v1.14.0-rc3 in the changelog and release notes.

CHANGELOG.md
Unreleased changes go mixed up with the released changes during merge of #1382. This PR fixes the `Unreleased` section.
---
=> correct unreleased changelog entries

CHANGELOG.md, RELEASE_CHANGELOG.md
In the `release/v1.14.x` branch, update the changelog to combine the 1.14.0 release candidate entries into a single `v1.14.0` entry. Update the release changelog to match.
---
=> Combine the 1.14.0 release candidate changelog entries.

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.14.1` in the changelog and release notes.
---
=> Mark v1.14.1 in the changelog and release notes.

scripts/initialize.sh
Initialization script fails due to a reference to a removed type on main.  This removes that reference allowing the script to complete successfully.
closes: #XXXX
---
=> Remove obsolete type from initialization script

CHANGELOG.md
Update the changelog in `main` to reflect the `v1.14.1` release.
---
=> Add v1.14.1 section to changelog.

CHANGELOG.md, x/attribute/client/cli/cli_test.go, x/attribute/client/cli/query.go
=> Add cli query command for account addresses by attribute name

app/upgrades.go, x/attribute/keeper/keeper.go, x/attribute/keeper/keeper_test.go
=> Add upgrade handler to populate lookup table

CHANGELOG.md
Update the changelog in `main` to reflect the `v1.15.0-rc1` release.
---
=> Mark v1.15.0-rc1 in the changelog.

go.mod, go.sum
Bump wasmd to `v0.30.0-pio-2` (from `v0.30.0-pio-2-rc2`).
---
=> Bump wasmd to v0.30.0-pio-2 (from v0.30.0-pio-2-rc2).

CHANGELOG.md, go.mod, go.sum, internal/antewrapper/min_gas_prices_decorator_test.go, internal/antewrapper/msg_fees_decorator_test.go, internal/antewrapper/prov_fee_test.go, internal/pioconfig/provenanceconfig_test.go, internal/provwasm/simulation.go, x/marker/client/cli/tx.go, x/metadata/client/cli/helpers_test.go, x/metadata/keeper/mocks_test.go, x/name/handler_test.go, x/name/keeper/msg_server_test.go
Bumps wasmvm to 1.1.2 and updates wasmd to the latest pio-release with the wasmvm update.
closes: #1484
---
=> Bump wasmvm version

CHANGELOG.md, go.mod, go.sum, internal/antewrapper/min_gas_prices_decorator_test.go, internal/antewrapper/msg_fees_decorator_test.go, internal/antewrapper/prov_fee_test.go, internal/pioconfig/provenanceconfig_test.go, internal/provwasm/simulation.go, x/marker/client/cli/tx.go, x/metadata/client/cli/helpers_test.go, x/metadata/keeper/mocks_test.go, x/name/handler_test.go, x/name/keeper/msg_server_test.go
Backport of #1486 to `release/v1.15.x`.
---
=> Backport: Bump wasmvm version (#1486)

CHANGELOG.md, docs/transaction_proposal.md
Added documentation that includes a tutorial on how to propose a transaction that will be ran by the governance module.
closes: #441 
---
=> Added documentation for proposing a transaction.

CHANGELOG.md, app/app.go, go.mod, internal/provwasm/query_plugins.go, internal/provwasm/stargate_whitelist.go
Backport of #1482 to `release/v1.15.x`.
---
=> Backport: add stargate query handler to wasmkeeper (#1482)

CHANGELOG.md, docs/transaction_proposal.md
Backport of #1489 to `release/v1.15.x`.
---
=> Backport: Added documentation for proposing a transaction. (#1489)

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.15.0-rc2` in the changelog and update the release changelog.
---
=> Mark v1.15.0-rc2 in the changelog.

CHANGELOG.md
Mark `v1.15.0-rc2` in the changelog
---
=> Mark v1.15.0-rc2 in the changelog

app/upgrades.go
Add upgrade entries for `quicksilver-rc2` and `quicksilver`.
---
=> Add upgrade entries for quicksilver-rc2 and quicksilver

x/marker/spec/01_state.md
=> Add documentation for required attributes

x/marker/spec/01_state.md
Add missing required attribute spec documentation.
closes: #XXXX
---
=> Backport: Add documentation for required attributes (#1516)

app/upgrades.go
Backport of #1510 to `release/v1.15.x`.
---
=> Backport: Add upgrade entries for quicksilver-rc2 and quicksilver. (#1510)

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark v1.15.0-rc3 in the changelog and release notes.
---
=> Mark v1.15.0-rc3 in the changelog.

CHANGELOG.md, x/marker/keeper/keeper_test.go, x/marker/keeper/send_restrictions.go, x/marker/keeper/send_restrictions_test.go
Checks if the receiving address is the marker escrow account and if so checks the from address to determine if it has deposit access.
closes: #1525 
---
=> marker deposit restriction fix

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.15.0` in the changelog and release notes in the `release/v1.15.x` branch.
---
=> Mark v1.15.0 in the changelog.

CHANGELOG.md, go.mod, go.sum
Bumped ibc-go to 6.1.1.
closes: #1562
---
=> bumped ibc-go to 6.1.1

CHANGELOG.md, x/marker/spec/01_state.md, x/marker/spec/03_messages.md, x/marker/spec/10_governance.md
Marker module spec had outdated spec documentation.  Updated to a new proto blob and line numbers.
closes: #1580
---
=> Update marker spec proto samples 

CHANGELOG.md
Mark` v1.16.0-rc1` in the changelog in main.
---
=> Mark v1.16.0-rc1 in the changelog.

CHANGELOG.md, x/attribute/client/cli/tx.go
Adds the Update Account Attribute Expiration command to the CLI.
closes: #1592 
---
=> Added NewUpdateAccountAttributeExpirationCmd to CLI

CHANGELOG.md, x/attribute/client/cli/tx.go
Backport of #1593 to `release/v1.16.x`.
---
=> Backport: Added NewUpdateAccountAttributeExpirationCmd to CLI (#1593)

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark v1.16.0 in the changelog, and update the release changelog as well.
---
=> Mark v1.16.0 in the changelog.

CHANGELOG.md, networks/ibc/docker-compose.yml
Updated ibcnet ports to make debugging easier.
closes: #1622
---
=> Update ibcnet ports

CHANGELOG.md, app/upgrades.go, app/upgrades_test.go, go.mod, x/attribute/keeper/keeper.go, x/attribute/keeper/keeper_test.go, x/marker/keeper/keeper_test.go, x/marker/keeper/marker.go
Remove the quicksilver upgrades and add ones for saffron with just the standard upgrade stuffs.
---
=> Remove quicksilver upgrades and add saffron

protoBindings/README.md, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Attribute.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Auth.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Bank.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/FeeGrants.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Governance.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Markers.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Metadata.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/MsgFees.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Names.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Tendermint.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Transactions.kt, protoBindings/bindings/kotlin/src/main/kotlin/io/provenance/client/protobuf/extensions/Wasms.kt
For the Kotlin proto bindings:
Surface existing extension methods in the Provenance coroutine-based client for feature parity.
---
=> kotlin: Add existing extension methods to Provenance coroutine-based client for feature parity

x/oracle/spec/README.md
Adds a missing Acknowledgement section to the Oracle module's README.
closes: #1721
---
=> Add Acknowledgement section to Oracle README.

CHANGELOG.md, app/upgrades.go, app/upgrades_test.go, x/ibchooks/marker_hooks.go
=> IBC denom metadata creation fix

CHANGELOG.md, RELEASE_CHANGELOG.md
Update the changelog and release notes (in `release/v.1.17.x`) to reflect the full `v.1.17.0` release.
---
=> Mark v1.17.0 in the changelog

CHANGELOG.md, README.md, x/README.md, x/attribute/spec/03_events.md, x/attribute/spec/README.md, x/exchange/spec/README.md, x/hold/spec/README.md, x/ibchooks/README.md, x/marker/spec/07_events.md, x/marker/spec/README.md, x/metadata/spec/04_authz.md, x/metadata/spec/README.md, x/msgfees/spec/README.md, x/name/spec/04_events.md, x/name/spec/README.md, x/oracle/spec/README.md, x/reward/spec/03_state_transitions.md, x/reward/spec/06_events.md, x/reward/spec/README.md, x/trigger/spec/README.md
These changes allow the contents of the spec folders to be pulled into the developer portal and rendered into the docusaurus application. The headings help with setting up the sidebar text.
---
~- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#pr-targeting))~
~- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.~
~- [ ] Wrote unit and integration [tests](https://github.com/provenance-io/provenance/blob/main/CONTRIBUTING.md#testing)~
~- [ ] Added relevant …
=> Changes needed to make the docs render in developer portal

CHANGELOG.md, cmd/provenanced/cmd/export_test.go, cmd/provenanced/cmd/genaccounts.go, cmd/provenanced/cmd/genaccounts_test.go, cmd/provenanced/cmd/pre_upgrade_test.go, cmd/provenanced/cmd/root.go, cmd/provenanced/cmd/testnet.go, cmd/provenanced/cmd/testnet_test.go, networks/dev/blockchain-dev/entrypoint.sh, scripts/initialize.sh, testutil/mocks/codec.go, testutil/network.go
closes: #1757 
This PR adds some genesis commands for adding a market to genesis. It also uses those to add a market to our various local environments (e.g. `make run`).
---
=> Add a market to our test/dev chains.

CHANGELOG.md, x/marker/keeper/keeper.go, x/marker/keeper/keeper_test.go, x/marker/types/key.go, x/marker/types/key_test.go
This PR updates the RemoveMarker keeper method to remove the marker's SendDeny list from the store.
closes: #1666
---
=> Remove all marker entries from send deny store when deleted

CHANGELOG.md, x/marker/client/cli/cli_test.go, x/marker/client/cli/tx.go
Updates the marker proposal transaction to do nothing, and instead redirect the user to the gov command to make a proposal.
closes: #1797
---
=> Deprecate marker proposal transaction

CHANGELOG.md, README.md, x/README.md, x/attribute/spec/03_events.md, x/attribute/spec/README.md, x/exchange/spec/README.md, x/hold/spec/README.md, x/ibchooks/README.md, x/marker/spec/07_events.md, x/marker/spec/README.md, x/metadata/spec/04_authz.md, x/metadata/spec/README.md, x/msgfees/spec/README.md, x/name/spec/04_events.md, x/name/spec/README.md, x/oracle/spec/README.md, x/reward/spec/03_state_transitions.md, x/reward/spec/06_events.md, x/reward/spec/README.md, x/trigger/spec/README.md
Backports some docs changes to `release/v1.17.x`:
* #1763 
* #1765 
---
=> Backport: Docs Fixes: #1763, #1765.

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.17.1` in the changelog and release notes.
---
=> Mark v1.17.1 in the changelog and release notes.

CHANGELOG.md, app/upgrades.go, app/upgrades_test.go, x/marker/keeper/keeper.go, x/marker/keeper/keeper_test.go, x/marker/types/key.go, x/marker/types/key_test.go
Add nav unit conversion to the 1.18 upgrade handler.
closes: #1815
---
=> Add nav unit conversion to upgrade handler.

CHANGELOG.md, app/app.go, app/app_test.go
=> add filtering of nil events from begin blocker

CHANGELOG.md
Mark v1.18.0-rc1 in the changelog (on `main`).
---
=> Mark v1.18.0-rc1 in the changelog.

CHANGELOG.md, app/app.go
Adds the PreBlocker to app.go from #1760.
---
=> Add PreBlocker to v0.50.

CHANGELOG.md, RELEASE_CHANGELOG.md
This PR marks `v1.18.0-rc3` in the changelog and release notes in `release/v1.18.x`.
---
=> Mark v1.18.0-rc3 in the changelog and release notes.

CHANGELOG.md, RELEASE_CHANGELOG.md
This PR combines the `v1.18.0-rc` changelog entries into a single `v1.18.0` entry (in both the changelog and release notes).
---
=> Mark v1.18.0 in the changelog and release notes.

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.19.0-rc1` in the changelog and release notes on the `release/v1.19.x` branch.
---
=> Mark v1.19.0-rc1.

.github/workflows/docker.yml
This PR backports #2052 to `release/v1.19.x`.
---
=> Backport: fix(ci): heighliner image build (#2052).

CHANGELOG.md, RELEASE_CHANGELOG.md
This PR marks `v1.19.0-rc2` in the changelog and release notes on the `release/v1.19.x` branch.
---
=> Mark v1.19.0-rc2.

CHANGELOG.md, RELEASE_CHANGELOG.md
This PR marks `v1.19.0-rc3` in the changelog and release notes on the `release/v1.19.x` branch.
---
=> Mark v1.19.0-rc3

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark `v1.19.0-rc4` in the changelog on `release/v1.19.x`.
---
=> Mark v1.19.0-rc4.

.github/workflows/docker.yml
This PR backports the following to `release/v1.20.x`:
* #2184 
---
=> Backport: fix(ci): heighliner build #2184.

CHANGELOG.md, RELEASE_CHANGELOG.md
Mark v1.22.0 in the changelog and release notes in `release/v1.22.x`.
---
=> Mark v1.22.0
